package year2024

fun main() {
//    val parsed = sampleInput12.map { it.split("").filter { it.isNotEmpty() } }
//    val parsed = sampleInput122.map { it.split("").filter { it.isNotEmpty() } }
//    val parsed = sampleInput125.map { it.split("").filter { it.isNotEmpty() } }
//    val parsed = sampleInput123.map { it.split("").filter {it.isNotEmpty()}}
    val parsed = realinput12.map { it.split("").filter {it.isNotEmpty()}}
//    val parsed = realInput12gmail.map { it.split("").filter {it.isNotEmpty()}}

//    val distinct = parsed.flatten().toSet()

    val regionsByLetters = hashMapOf<String, ArrayList<List<Pair<Int, Int>>>>()
    val prices = arrayListOf<Long>()
    var regions = arrayListOf<ArrayList<Pair<Int, Int>>>()
    var region = arrayListOf<Pair<Int, Int>>()

    fun recursion(previousArray: ArrayList<Pair<Int,Int>>, currentY: Int, currentX: Int, prevY : Int, prevX: Int, letter: String) :List<Pair<Int,Int>> {
        println("$currentY - $currentX")
        val current = if (parsed.getOrNull(currentY)?.getOrNull(currentX) == letter) Pair(currentY, currentX) else null
        current?.let { previousArray.add(it) }

        val bottom = if (parsed.getOrNull(currentY +1)?.getOrNull(currentX) == letter
            && currentY + 1 != prevY
            && !previousArray.contains(Pair(currentY +1, currentX))
            ) {
            recursion(previousArray, currentY+1, currentX, currentY, currentX, letter)
        } else null

        val top = if (parsed.getOrNull(currentY -1)?.getOrNull(currentX) == letter
            && currentY - 1 != prevY
            && !previousArray.contains(Pair(currentY -1, currentX))
            )         {
            recursion(previousArray, currentY-1, currentX,  currentY, currentX,  letter)
        } else null

        val left = if (parsed.getOrNull(currentY)?.getOrNull(currentX-1) == letter
            && currentX - 1 != prevX
            && !previousArray.contains(Pair(currentY , currentX-1))
            )       {
            recursion(previousArray, currentY, currentX-1,  currentY, currentX,  letter)
        } else null

        val right = if (parsed.getOrNull(currentY)?.getOrNull(currentX+1) == letter
            && currentX + 1 != prevX
            && !previousArray.contains(Pair(currentY , currentX+1))
            )        {
            recursion(previousArray, currentY, currentX+1,  currentY, currentX,  letter)
        } else null



        val result = arrayListOf<Pair<Int,Int>>()
        result.addAll(previousArray)
        bottom?.let { result.addAll(it) }
        top?.let { result.addAll(it) }
        left?.let { result.addAll(it) }
        right?.let { result.addAll(it) }

//        return result
        return result.toSet() .toList()
    }

    for (y in 0..parsed.size-1){
        for (x in 0..parsed[0].size-1) {
            val letter = parsed[y][x]
            println("$letter - $y, $x, - ${regionsByLetters.values.flatten().flatten()}")
            if (regionsByLetters.values.flatten().flatten().any { it.first ==y && it.second == x }) {
                continue
            } else {

                val arr = recursion(arrayListOf(), y,x, -1, -1, letter)
                println("$letter - ${parsed[y][x]} - $arr")
                val regionsForLetter = regionsByLetters.getOrDefault(letter, null)
                if (regionsForLetter == null) {
                    regionsByLetters[letter] = arrayListOf(arr)
                } else {
                    regionsForLetter.add(arr)

                }
            }

        }
    }




    println("------------------")
    println(regionsByLetters)
    regionsByLetters.keys.forEach { println("$it - ${regionsByLetters[it]}") }
    println("------------------")

//    regionsByLetters.
    regionsByLetters.keys.forEach { letter ->

//        println("$letter - ${regionsByLetters[letter]}")
//        if (letter == "O")
        regionsByLetters[letter]?.forEach { coords ->
//                    val minY = coords.map { it.first }.min()
//        val minX = coords.map { it.second }.min()
//        val maxY = coords.map { it.first }.max()
//        val maxX = coords.map { it.second }.max()

            val area = coords.size
//        val perimeter = (maxY - minY +1)*2 + (maxX - minX +1)*2
            var perimeter = 0
            val internalPairs = arrayListOf(
                Triple(Pair(0,-1),Pair(-1,0), Pair(-1,-1)),
                Triple(Pair(-1,0),Pair(0,+1), Pair(-1,+1)),
                Triple(Pair(0,+1),Pair(+1,0), Pair(+1,+1)),
                Triple(Pair(+1,0),Pair(0,-1), Pair(+1,-1)),
            )
            for (point in coords) {
                val internal = internalPairs.map {
                    val v1 = coords.contains(Pair(point.first + it.first.first, point.second + it.first.second))
                    val v2 = coords.contains(Pair(point.first + it.second.first, point.second + it.second.second))
                    if (
                    !coords.contains(Pair(point.first + it.first.first, point.second + it.first.second)) &&
                    coords.contains(Pair(point.first + it.third.first, point.second + it.third.second))
                    ) 1 else 0
                }
                val external = internalPairs.map {
                    val v1 = !coords.contains(Pair(point.first + it.first.first, point.second + it.first.second))
                    val v2 = !coords.contains(Pair(point.first + it.second.first, point.second + it.second.second))
                    if (
                        !coords.contains(Pair(point.first + it.first.first, point.second + it.first.second)) &&
                        !coords.contains(Pair(point.first + it.second.first, point.second + it.second.second)) &&
                        !coords.contains(Pair(point.first + it.third.first, point.second + it.third.second)
                        )
                    ) 1 else 0
                }
                perimeter = perimeter + internal.sum() + external.sum() // + top + bottom + left + right
            }


            val price = area.toLong() * perimeter.toLong()
            prices.add(price)
            println("$letter - area $area - perimeter $perimeter - price $price")

        }
    }

    println("result 2 = ${prices.sum()}")
    println("==============")
    println(regionsByLetters.values.flatten().size)
    println(regionsByLetters.values.flatten().distinct().size)

}

//val sampleInput12 = arrayListOf(
//    "AAAA",
//            "BBCD",
//            "BBCC",
//            "EEEC",
//)
//val sampleInput122 = arrayListOf(
//    "OOOOO",
//            "OXOXO",
//            "OOOOO",
//            "OXOXO",
//            "OOOOO",
//)
val sampleInput124 = arrayListOf(
    "EEEEE",
            "EXXXX",
            "EEEEE",
            "EXXXX",
            "EEEEE",
)
val sampleInput125 = arrayListOf(
    "AAAAAA",
            "AAABBA",
            "AAABBA",
            "ABBAAA",
            "ABBAAA",
            "AAAAAA",
)
//val sampleInput123 = arrayListOf(
//    "RRRRIICCFF",
//            "RRRRIICCCF",
//            "VVRRRCCFFF",
//            "VVRCCCJFFF",
//            "VVVVCJJCFE",
//            "VVIVCCJJEE",
//            "VVIIICJJEE",
//            "MIIIIIJJEE",
//            "MIIISIJEEE",
//            "MMMISSJEEE",
//)
//
////+ R - area 12 - perimeter 18 - price 216
////- C - area 15 - perimeter 32 - price 480
////A region of C plants with price 14 * 28 = 392.
////A region of C plants with price 1 * 4 = 4.
////+ S - area 3 - perimeter 8 - price 24
////+ E - area 13 - perimeter 18 - price 234
////+ F - area 10 - perimeter 18 - price 180
////+ V - area 13 - perimeter 20 - price 260
////- I - area 16 - perimeter 28 - price 448
////- I - area 2 - perimeter 6 - price 12
////+ J - area 11 - perimeter 20 - price 220
////+ M - area 5 - perimeter 12 - price 60
//
//val realinput12 = arrayListOf(
//    "XXXXXUUUNNNNNNNNNNNNNNNNQQQQQQQQQJJJJJJJJJJJJJJJJCCCAAAAAAAAAAAAOVVVVVVVVVVVVVVVVVVLLLLLLLLKKKKGGGGGGGGGGGGGGGGGGGKKKKKKKKKKKKKKKKKKKKKKKKKK",
//            "XXXUXXUUUUNNNNNNNNNDNNDGQQQQQQQQQJJJJJJJJJJJJJJJJJJCCCAAAAAAAAAYVVZVVVVVVVVVVVVVVVVVLLLLLLLLKKKGGGGGGGGGGGGGGGGGGGKKKKKKKKKKKKJKKKKKKKKKKKKK",
//            "XUUUUUUUUUENNNNNNNNNNNDCCCCCCCCQQJJEJJJJJJJJJJJJJJCCAAAAAAAAAAAZZZZVVZVVVVVVVVVVVVVVLLLLLLLLKGGGGGGGGGGGGGGGGGGGGKKKKKKKKKKKKAKKKKKKKKKKKKKK",
//            "UUUUUUUUUUUYNNNNNNNNNNNCCCCCCCCQJJJJJJJJJJJJJJJJJJCAAAAAAAAAAAAZZZVVVVVVVVVVVVVVVVVVLLLLLLLLLLZGGGGGGGGGGLLGGGGGGKKKKKKKKKKAAAAKKKKKKKKKKKKG",
//            "UUUUUUUUUKKNNNNNNNNNNZZCCCCCCCCJJJJJJJJJJJDDJJJJJJCAAAAAAAAAAAAHZZVVVVVVVVVVVVVFVVMVVLLLLLLLLLMAAAGGGGLLGLLGGGGGGGGGKKKKKKKAAAAKKKKKKKKKKKKG",
//            "UUUUUUUUUKUANNNNNNNNNZZCCCCCCCCQJJJJJJJJJDDDDJJJJJCJJAAAAAAAAAAHZZVVVVVVVVVVVVVVVVMMLLLLLLLGLLMAAAAGGGLLGLLLLLLLGGGGKKKKKKKAAAAKKKKKKKKKKKKG",
//            "UUUUUUUUUUUUUNNNNNNNNZZCCCCCCCCQQQQJJDDDDDDDDDJJJJJJAAAAAAAAAAAZZZVVVVVVVVVVVVVVVVMMLLLLLLGGGMMAALGGGLLLLLLLLLLLGGGKRKKKKKKAPPPPPKKKKKKKKKKG",
//            "UUUUUUUUUUUUNNNNNNNNNZZCCCCCCCCCCCCCCCCCDDDDDDJJJJJJAAAAAAAAZZZZZZZVVVVVVVVVVVVVVVMMMLLLLLGGGMAAALLLLLLLLLLLLLLLKKKKKKKKKKKPPPPPKKKKKKKKKGGG",
//            "UUUUUUUUUUUZNYNNSNNNNZZCCCCCCCCCCCCCCCCCDDDDDDEJJJJJAAAAAAAAAZZZZZZVVVVVVVVVVVVVVVMMMLLLLLGMMMMMALJLLLLLLLLLLLLLKKKKKKKOKPKPPPPKKKKKKGGKGGGG",
//            "UUUUUUUUUUUZNSNZZZZZZZZCCCCCCCCCCCCCCCCCDDDDDDJJJJJAAAAAAAQAAAZZZZZZZMFMMMMMMMMMMMMMMMLLLGGMMMMMMMLLLLLLLLLLLLLLKKKKKKKKPPPPPPPPKKPKKGGKGGGG",
//            "UUUUUUUUUUMSSSZZZZZZZZZCCCCCCCCCCCCCCCCCDDDDDJJJJJJAAAAAAAQZZZZZZZZZZFFMFMMMMMMMMFFMMLLLLGAMMMMMMMMMLLLLLLLLLLLLLKKKKKKPPPPPPPPPKKPKKGGGGGGG",
//            "UUUUUUUUUMMSSSZZZZZZZZZCCCCCCCCCCCCCCCCCDDDJJJJJJJJJAAJAAQQZZZZZZZZZZFFFFMMMMMMMMFIAMMAAAAAMMMMMMMMLLLLLLLLLLLLLLKFKKKKEPPPPPPPPPKPKGGGGGGGG",
//            "OOUUUUUUSSSSSSZZZZZZZZZCCCCCCCCCCCCCCCCCDDDJJJJJJJJJJJJAAQQNNNZZZZZZZFFFFFFFFFFFFFFAAAAAAAAMMMMMMMMXLLLLLLLLLLLLKKUUUUUPPPPPPPPPPPPPPPGGGGCC",
//            "OUUUUOUUUPSSSSZZZZZZZZZZZZZZZQQCCCCCCCCDDSDDCJJJJJJJJAAAAAQNZZZZZZZZZFFFFFFFHFFFFFFFAAAAAAAAMMMMMMCCCLCLLLLLLLLLLTUUUUUPPPPPPPPPPPPPPPPGGGCC",
//            "OOUGGGGUUSSSSZZZZZZZZZZXXXXJJJJJJCCCCCCDDSSCCJJJJJJJJAAAAANNNNZZZZZBPPFFFFFFFFFFFFFFAAAMAAAAAMMMMMMCCCCCLLLLLLLLLMMUUUPPPPPPPPPPPPPPPPPGGGCC",
//            "OGGGGGGLLLLSSZZZZZZZZZZXXXJJJJJJJCCCCCCSSSSSJJJJJJJJJJJAAANNNNNZZZNPPPPFFGPPFFFFFFFAAAAMAAMMAMMMMMMCCCCCCOOOLLLLLLMMUUUPPPPPPPPPPZPPPPCCCCCC",
//            "OGZZGGGLLLLLSZZZSSSXXXXXXXXXJJJJJCCCCCCSSSSWJJJJJJJJJJPJANNNNNZZZNNPPPPPFPPPPPFFFVHHAAMMMMMMMMMCMCICCCCCCCCOOLTOOLMMMUUPPPPPPPZPPZPCCICCCCCP",
//            "OGGGGGGGGLLSSZZZSSSXXXXXXXXXJJJJJCCCCCCSSSSSJJJJJJJJJJJJNNNNNZZZZZNNPPPPPPPPPPPVVVVVMMMMMMMMMMCCCCCCCCCCCOOOOOOOOOMMUUUUPPPPPZZZZZZCCCCCCCCP",
//            "SGGGGGGGGLSSSZZZSXXXXXXXXXXJJJJJJCCCCCCJSSSRJJJJJJJNJJJNNNNNNNZZZNNPPPPPPPPPPPPVVVVVMVMMMMMMMCCWCCCCCCCCCCCOOOOOOOOOUUUUPPPPPNNZZZCCCCCCCCCP",
//            "SGGGGGGGSSSSSZZZSUXXXXXXXJJJJIJJJCCCCCCJWWWWJJJJJJJJLJJNNNNNNNNNNNNNPPPPPPPPPPPVVVVVVVMMMMMCCCCCCCCCCCCCCCCCCOOOOOOOUUUPPPPPPNNNNCCCCCCCCCPP",
//            "SSSGGGGGGGVSSSSSUUXXXXXXXJJJIIJJJCCCCCCWWWWWJJJJJJJJJJNNFNNNNNNNNPPPPPPPPPPPPPVVVVVVVMMMMMMMRRRRCCCCCCCCCCCCCOOOOUOOUUUPUTNNNNNNNCCCCCCCPCPP",
//            "SSSSZGGGGGRYSSSRXXXXXXXXXXJJJJJJJJJJJJWWWWWWWJJAJJJJJNNFFNNNNNNNNPPPPPPPPPPPPPVVVVVVVMMMMMMMMRRRCCCCCCCCCCCCCOOOOUUUUUUUUTNNNNNNNNCCCCCCPPPP",
//            "SSSZZGHGGGRRJSRRGXXXXXXXXXXJJSSJJJJJJJWWWWWWWJJAJJJJJJFFNNNNNNNNNNPPPPPPPPPPPPPVVVVVVMMMMMMMRRRRRCCCCCCCCCCCCOOOUUUUUUUUUTTTTTNNNNNCCCCPPPPP",
//            "SSQQZZGGGGRRRRRRRXXXXXXXXRXRRJJJJJJJJWWWWWWWWWJJJJJJJJJFFFFFFNNANNNPPPPPPPPPVVVVVVVVVMMMMMRRRRRRRCLLCLLLLLCCCCOOOUUUUUUUTTTTTTNNPPNCCPPPPPPP",
//            "QQQQQZZGGGRRRRRRRXXXXXRRRRRRRRJJJJJJWWWWWWWWWWWWWJJJJFFFFFFFFAAAAAPPPPPPPPPVVVVVVVVVVVVDMMMRRRRRRRLLLLLLLLCLCLOOUUUUUUUUUUUUUUUPPPPPPPPPPPPP",
//            "QQQQZZQQZRRRRRRRRRRRRRRRRRRRRRRJJJJJSWWWWWWWWWWWWWJJJFFFFFFFFAAAAAPPPPPPPPVVVVVVVVVVVVDDMDRRRRRRRRXXXXLLLLLLLLUOUUUUUUUUUUUUUUUPXPPPPPPPPPPP",
//            "QQQQQQQQQRRRRRRRRRRRRRRRRRRRRRRRJVJSSWWWWWWWWWWWWWFFFFFFFSFAAAAAAAPAPPPPPPVVVVVVVVVVDVDDDDRRRRRRRRLXLLLLLLLLLLUUUUUUUUUUUUUUUUUUXXPPPPPPPPPP",
//            "QQQQQQQQQRRRRRRPRRRRRRRRRRRRRRRRVVWWWZWWWWWWWWWWWWJFFFFFFFAAAAAAAAAAVPPPPPVVVVVVVVVVDDDDDDHRRRRRRELLLLLLLLLLLSSUUUUUUKUUUUUUUUKUXPPPPPPPPPPP",
//            "QQQQQDQDGRSPRPPPPRRRRRRRRRRRRRRRRVVVWWWWWWWWFFJJJJJJJJJFFAAAAAAAAAAAAAPPVVVVVVVVVVVDDDDDDRRRRRRRRRRRLLLLLLLLLLSUUUUUKKKUUKKKUUKUUPPPPPPPPPPP",
//            "QDDQDDQDGGPPPPPPPRRRRRRRRRRRRRRRRVVWWWWWWWWWDFFJJFFFFJJFFAAAAAAAAAAAAAAPVVVDDVVVVVDDDDDDDRRRRRRRRRRRLLLLLLLLLSSSUUSUUKKKKKKKKKKUYYPPPPPPPPPP",
//            "QDDDDDDDGPPPPPPPPRRRRRRRRRRRRRRRRVVVVWWWWWQQFFFJFFFFFFFFFAAAAAAAAAAAAABBHDDDDVVDVDDDDDDDDRFRRRRRRRRLLLLLLLLLLLSSSSSSKKKKKKKXXDYYYYYPPPPPPPPP",
//            "DDDDDDDGGGPWPPPPPPPPRRRRRRRRRRRRRRVVVWWQQWQQQFFJFFFFFFFFAAAAAAAAAAAAAUBBHBBBDDDDDDDDDDDDDDRRRRRRRRRLLLLLLLLLLSSSSSSSKKKKKKKKXDYYYYYPYPPPPPPP",
//            "DDDDDDDDDGPWPPPPPPPPPRRRRRRRRRRRRRVRWWWWQQQQQFFFFFFFFFZFAAAAAAAAAAAAABBBBBBBBBBDDDDDDDDDDDDDYRRRRRRRLLLLLLLJLLSSSSSSKKKKKKKKXDDDYYYYYYYPPPKP",
//            "DDDDDDDDDDDDPPPPPPPPPRRRRRRRRRRRRRRRRSSQQQFFFFFFFFKKFFFHHHAAAAAAAAAAABBBBBBBBBBBDDDDDDDDDDDDRRRRRRLLLLLLLLSSSSSSSSSUKKKKKKKKDDDDYYYYYYYPPPPY",
//            "DDDDDDDDDDAAPPPPPPPPPRRRRRRRRRRRRRRRSSQQQEEGFFFFHHFFFFHHHHAAAAAAAAABBBBBBBBBBBBBDDDDDDDDDDDDRRRRRRRLLLHHLLLSSSSSSSSSKKKKKKGGDDDDDDYYYYYPPPYY",
//            "DDDDDDDDDDAAAPPPPPPPPPRRRNNRRRRRRRRSSQQQQEEEFFFHHHHHFHHHHHHHAAAABBBBBBBBBBBBBBBBBDDDDDDDDDRRRRRRRRRLLLHHHLSSSSSSSSSSKKKKKKDDDDDDDDYYYYYYYYYY",
//            "DDDDDDDDDDDAAPPPPPPPPRRRNNNRRRRRRRQQSQQQQEEEFFFHHHHHHHHHHAAAABBBBBBSSBBBBBBBBBBBBDDDDDJJJJDDRRRRRRRHLLHLLLLSSSSSSSSKKKKKKKUDDCDDDDYYYYYYYYYY",
//            "DDDDDDDDDDAAAPPPPPIIIRRRRNRRRRRRRRQQQQQQQEEEFFFHHHHHHHHHHHHAABBBBBBBBYBTBBBBBKBRBDDDDJJMMJJDRRSSRRRHLHHHHHLQQQSSSSSSKKKKKKDDDDDDDYYYYYYYYYYY",
//            "DDDDDDDDDDDAAPPPPPPQIIIRRRRRRRRRRQQQQQQNNQEHHFFFHHHHHHHHHHHHHBBBBBBBYYYBBBBBBBBRRRRDDJJJJJJRRRRRRRHHHHHHJJLQQQSQQSSSSSSKKKDDDDDDDYYYYYYYYYYY",
//            "DDDDDDDDNNDQAPPPPPQQQIIRQRRRRRRRRRQQQQQQNNSHHFHHHHHHHHHHHHHHHBDBBBYYYYYBBBBBBRRRRTDDJJJJJJJTRRRRRRHHHHHHHQQQQQQQQSSSSSSSDDDDDDDDDYYYYYYYYYYY",
//            "DDDDDDDDNNNQAPPNPPPQQIIQQHRRRRRRRRQQQQQQQNSHHHHHHHHHHHHHHHHEHBDDGBBGWWWBBBBBBBRRRTTTTJJJTTTTRHHHHHHHHHHHHHQQQQQQQSSSSSSSSSDDDDDDYYYYYMYYMYYY",
//            "DDDDDDDNNNNQQQPPQQQQQQQQQHHHHHXXXXXQQQQQQNNNHHXXHHHHHHHRRHRRRRDDGBBGWWWWBBBWWBRRRTTTTTTTTTTTTHHHHHHHHHHHHQQQQQQQQSJJSSSSSSSDDDDDYYMYMMMMMMYM",
//            "DDDIIDDDDNNQQQQPQQQQQQQQQQHHHXXXXXQQQQQQQNNEEEHHHHHHHHHRRRRRRRGGGGGGWEWWWBBWWBWWWWRTTTTTTTTTHHHHHHHHFHHLQQQQQQQQQQJJJSSSSDSDIIDDYYMMMMMMMMYM",
//            "DDDDDDDHNNNNQQQQQQQQQQQQHHHHXFXXXXXXXNNNNNNNNHHHHHHHHHHRRRRRRUUGGGGGGGGWWWWWWWWWWWRRTTTTTTTHHHHHHHHFFHGQQQQQQQQQJJJJJJSSSDDDIIYYYYMMMMMMMMMM",
//            "QDDDDNNNNNNNNQQQQQQQZZQQQHHXXXXXXXXXXNUNNNNNNNNPNYYHHHRRRRRRRRUGGGGGGGGWWWWWWWWWWWWWTTTTCTTTHHHHHHHHHGGGQQQQQQQJJJJJVJWSWKKKYIYYYYYMMMMMMMMM",
//            "QDDQNNNNNNNNNNNQQQQQZZLQHHXXXXXXXXXNNNNNNNNNNNNNNNYHHHRRRRRRRRRGGGGGGGWWWWWWWCWWWWCWTTTTCCTCHHHHHHGGHGGQQQQQQQJJJJJJVWWSWKKKYYYYYYYYMMMMMMMM",
//            "QQQQNNNNNNNNNQQQQQQQZZZZZXXXXXXXXXTNNNNNNNNNNNNNNNNNHHRRRRRRRGGGGGGGGGGWWWWCCCWWWCCQQCCCCCCCHVHHHHHGGGGQQQQQQQJJJJJJJWWWWWKKKQYYYYMMMMMMMMMM",
//            "QQQNNNNNNNNNNNQQQQQQQZZZZLXUWXXXXXNNNNNNNNNNNNNNNNNKKHRRRRRRRGGGGGGGGGGWWWCCCCCCCCCQQQCCCCCCVVVVVDDGGGQQQQQQQQJJJJJJJWWWWWLKLQQYQQNMMMMMMMMM",
//            "QQQQNNNNNNNNNNQQQZZZZZZZZZOWWXWXXWNNWNNNNNNNNNNNKKKKKKARRRRRRGGGGGGGGGGGWWWCCNCCCCCCQCCCCCCCCVVVVDGGGGKOQOKKQJJJJJJJWWWWWWLLLQQQQMMMMMMMMMMM",
//            "QQQNNNNNNNNNNNNQZZZZZZZZZZZZWWWWWWNWWWNNNNNNNNNNKKKKKKARRRRKKKKGGGGGGGGGGWWWCCCCCCCCCCCCCCCCCCVDDDDDGGKOOOKKQQJJJJJWWWWWWLLLLMQQQMMMMMMMMMMU",
//            "LQQQNNNNNNNNNNQQZZZZZZZZZTTTTWTWWWWWWWNNNNNNNNNNNKKKKKARRRRKKKKGGGGGGGGGWWWUCRCCCCCCCCCCCCCCJDDDDDDGGKKKKKKKKKJJJJJWWWWWWMLLLMQQTMMMMMMMMMMM",
//            "LNNNNNNNNNNNNQQQZZZZZZZZTTTTTWTWWWWWWWNNNNNNNNNNKKKKKKARRRRDKKKKKKGGGGGGWGUUCCCCCCCCCCCCCCCUCCDDDDDGDKKKKKKKKKJJJJTTTWWWMMMMMMMMMMMMMMMMMMMM",
//            "LLNNNNNNNNNNNNQQZZZZZZZZTTTTTTTTWWWWWWWNNNNNNNNNNKKKKKKGGRRDDKKKKKKKKGGGGGUUUUCCCCCCCCCCCCCCCCDDDDDDDNKKKKKKKKKKJYYTTTTMMTTMMMMMMMMMMMMMMMMM",
//            "LLLNTNNNNNTNQNQQCCZZZZZTTTTTTTTTWWWWWWWNNNNNNNNNNKNNKKKGGRRRDDKKKKKKKUGGGUUUUUCCCCCCCCCCCCCCCCDDDDDNNNNNKKKKKKKKBYYTTTTMTTTTTTMMMMMMMMMMMMMM",
//            "LLLLTTNNNNTTQQQQQQZZZZTTNTTTTTTWWWWWWNNNNNNNNNNNNGGGGKGGGGGCDKKKKKKKKUGGUUUUUCCCCCCCCCCCCCCCCCDDDDDDNNNNKKKKKKKKKYYTTTTTTTTTMMMMMMMMMMMMMMMM",
//            "LLLLLTNNNNTTQTQQTTTTTTTTTTTTTTTWWWWWWWNNNNNNNNNNNNGGGGGGGCCCCCKKKKKKUUUUUUUVUCCCCCCCCCCCLCCCCCDDDDDDDDDDKKKKKKKKYYYTTTTTTTTTNNNMMMMMMMKKMMMM",
//            "LLLLLTNNNNTTTTQTTTTTTTTTGTTTTTKKKWKKKWNNNNNNNNNNNNNGGGGGGGCCCCKKKKKKUUUUUUUVVCCCCCCCCCCLLCEECCDDDDDDDDDKKKKKKKYYYYYTTTTTTTTNNNNNKKKKKKKKKKKK",
//            "LLLLLTTTNNTTTHBTHTTTTTTTGTTTTKKKKKKKKWNNNNNNNNNNNNNGGGGGGGXCCCCKKKKKUUUUUUZVVCCCCCLCCLLLLLLEDDDDDDDDDDDKKKKKKKYYYYYTTTTTTTTTENNNKKKKKKKKKKKK",
//            "LLLLLLLTTTTHHHHHHHTTTTTGGTGKKKKKKKKKKWWNNNNNNNNNNNGGGGGGGGCCCCKKKBBKUVVVVZZVCCCCFFLLLLLALZBDDDDDDDDDDDDKKKKKKKYYYYYTTTTTTTNNNNNNNKKKKKKKKKKK",
//            "TTTTTTLTTTHHHHHHHHHTTTTTGGGKKKKKKKKKKWWGNNGNNNNNNNNNGGGGGGCCCCCKKKCCUVVVVVVVVVCFFFFLLLLAZZZZZDDDDDDDKKKKKKKKYYYYYYYYTTTTTTNNNNNNNKKPKKKKKKKK",
//            "TTTITTTTTTHHHHHHHHTTTTTTGGKKKKKKKKKKKGGGGGGNNNNNNNNNNGGGGCCCCCCCCCCCUUUVVVVVVVVVVFFLLLLAAZZZZZDVDDDKKKKKKYYYYYYMYYTTTYTTTTTNNNNNNNKKKKKCKKKN",
//            "TTIIIIIIIIIIIIIHHHTTTTTTTACKPKKKKKKPKGGGGGGGNNNNNNNNNGGGGCCCCCCCCCCCCUUVVVVVVVVVVVRHHLLLZZZZZZZZDKKKKKKKKYYYYYYMMYYYYYYTTTNNNNNNNNNKKKKKKKNN",
//            "TTTIIIIIIIIIIHHHHHHTTTTTAAKKKKKKKKPPPGGGGGGGGGNGGNNNNGGGXCCCCCCCCCCCCCCVVVVVVVVVVVRRRRRLLZZZZZZZDZZZKKMMKMMYMMMMMMYYYYYYYYNNNNNNNNNNNNKKNNNN",
//            "TTIIIIIIIIIIIIPHAATTTTTAAAUKKKKKTPPPGLLGGGGGGGGGNNNKKKGXXXKCCCCCCCCCCVVVVVVVVVVRRRRRREEZZZZZZZZZZZZZKKMMMMMMMMMMMMYYYYYYYYNNNNNNNNNNNNNNNNNN",
//            "TTIIIIIIIIIIIIIIAAATTTAAAUUUKKTTTTPPGGGGGGGGGGGSKKKKKKKXXXCCCCCCCCCCVVVVVVVVVVVVRRRRRRRZZZZZZZZZZZZZKKMMMMMMMMMMMYYYYYYYYYYNNNNNNNNNNNNNNNNN",
//            "IIIIIIIIEEEIIIIIAAAAAAAAUOUUKKJTTTPPGGGGGGGGGGGSKKKKKKXXXXCCUCCCCCCCVVVVVVVVVVVVRRRRRRRZZZZZZZZZZZZZKMMMMMMMMMMMMMYYYYYYYYYYNANNNNNNNNNNNNNN",
//            "EERIIEEEEEBEIIIAAAAAAAUUUUUUUUJJTTTJJJGGGGGGGGGGGKKKKKXXXXXXCCCCCCCCVVVVVVVVVVRRRRRRFRRZEZZZZZZZZZZZKKKMMMMMMMMMMMYYYYYYYZZZZZZZNNNNNNNNNNXX",
//            "EEEIIEEEEEEEEEEEEAAAAUUUUWWNUUJJTTTTJGGGGGGGGGGGGKKKKXXQXXXQCCCCCQCCVVVVVVVVVRJJRRRRRRRZEEEZZZZZZZZKKKMMMMMMMMMMMMYYYYYTTZZZZZZZNNNNANTNNXXX",
//            "EEECEEEEEYEEEEEAEAAAAUULLWWWWLTTTTTTTGGGGGGGGGGGGKKKKKKQXQQQCCQCQQCCVVVVVVVVRRRRRRRRRRRRERRZZZZUZKKKKKHMMMMMMMMMPMMTTTTTTZZZZZZZAANNATTXXXXR",
//            "EEECEEEEEEEEEEJAAAAAAAUOOOOWWLLTTTTVGGGGGGGGGGGKKKKKKKKQQQQQQQQQQQCCCVVVVVKKRRRRRRRRRRRRRRIPBZZUZKKKKHHMMMMMMMMMMTTTTTTTTZZZZZZZAANNAARRRRRR",
//            "EEEEEEEEEEEEEEAAAAAAAAUOOOOWWLLLQUTVGGGGGGGGGGKKKKKKKKKQQQQQQQQQQQQCVVVVVVKKKRRRRRRRRRRRRIIPPPPPPKKKKHHHHMMMMMMMMMTTTTTTTZZZZZZZAAANARRRRRRR",
//            "EEEEEEEEEEEEEEEVAAAAAAPOOOOLLLLQQQLQGGGKGKKKKGTTKKKKKKKQQQQQQQQQKQQCCVVVVVKKKRRRRRRRRRRRRRPPPPPLPKKHHHHHHMMMMMMMMMTTTTTTTTOAZZZZAAAAAARRRRRR",
//            "EEIEEEEEEEEEEEEEAAAAAAOOOLLLLQQQQQQQGGQKKKKKKEETTKKKKKQQQQQQQKKKKQQQVVVVVKKKKRRRRRRRRRRRRPPPPPPPPHHHHHHHHMMMMMMOMOTTTTTTTTHAZZZZAHAAARRRRRRR",
//            "CEIEEEEEEEEEEEEEAAAAAAALLLLLLQQQQQQQGGQKKKKKKEETEKKWWKQQQQQQKKKKKKQKKVVKKKKKKKKKKKKKRRRRRPPPPPPPPPHHHHHHHHMMMMMOOOOTTTTTTCCCCCCCCCAAARRRRRRR",
//            "BBBBEEEEEEEEEEAAAAAAAAAALLLQQQQQQQQQQQQQQQQKKEETEEWWWQQQQQQKKKKKKMKKKVVKKKKKKKKKKKKKRBRRHVHHPPPPPPHHHHHHHMMMMMMMMMTTTTTTTCCCCCCCCCAAAARRRRRR",
//            "BBBEEEWEEEEEEEEEAAAAAAAALLLQQQQQQQQQQQQQQKKKKEEEEEWWWWWQQQQKKKKKKKKKKKKKKKKKKKKKKKKKRBKRHHHHPPPPPPRHHHHHRQMIMMMMMQTTTTTTTCCCCCCCCCHRRRRRRRRR",
//            "BBBBEEEEEEEEAAAEAAAAAAAALLQQQQQQQQQQQQQQKKEEEEEEEEWWWWWWWKKKKKKKKKKKKKNKKKKKKKKKKKKKKKKRHHHHPPPPPPPHHHHHQQVMMMMPPTTTTTTTTCCCCCCCCCHRRRRRRRRR",
//            "BBBBEEHEEEEEAAAAAAAAAAALLLSZQQQQQQQQQQQQQQEEEEEENEEWWWWWKKKKKKKKKKKKKNNKNNCKKKKCKKKKKKKHHHHHPPPPPPPHHHHHQQQLMMMMPPTTTTTTTCCCCCCCCCOORRRRRRRR",
//            "BBHHHHHHEAAEAAAAAAAAAAAALLSZQQQQQQQQQQQQQQEEEEEEEEEEHWWWKKKKKKKKKKKKKKNKNNCCCCCCCCKKKKKKHHHHHHPPPPDHHSSHQQLLLLMPPPTTTTTTTCCCCCCCCCOORRRRRRRR",
//            "BBHHHHAHEAAAAAAAAAAAAAAAASSZQQQQQQQQQQQQQUEUEEEEEEEHHWWWWEKKKKKKKKKKKKNNNNCCCCCCCCKKKKKKHHHNNHPPPPPHHSSQQQLLMMMPPPTTTTTTTCCCCCCCCCOOOOORRRRF",
//            "BBHHHHAAAAAAASSAAAAAAAAAYSSSSQQQQQQQQQQQUUUUUEEEBEHHEEEEEEEKKKKKKKKKKKKKNNCCCCCCCCKKKKHHHHHNNNXPPPPHHSSQQLLMMMMPMPPTTTTTTOOOOHHOOOOOOOOORRRR",
//            "BBHHHHHHAAAASSSAAAAAAAYYYYSSSSSQQQQQQQQQQUUBBBBBBBHHHHEEEEEKKKKKKKKKKKKKNCCCCCCCCCCKKHHHHHNNNXXRRPXHSSSQQLMMMMMMMPPTTTTSZZOOOOOOOOOOOOOOORDD",
//            "BBHHHHHJJAAAASSSSSSSYAAYYYYSSSQQQQQQQRQQQUUUUUBBBBBHHHEEEEEEEEEKKKKOOZCZNCCCCCCCCCCKKKHHHHNNNXXXXXXXSSSMSSMMMMMMMPPTTTTTZZOOOOOOCOOOOOOOOOOD",
//            "HJHHHHJJJJAAASSSSSSSYYYYYYYYYYQQQRQQQRRRUUUUBBBBBBBBHHEEEEEEEXXXXXXXZZZZZCCCCCCCCCCCCHHHNNNNXXXXXXXSSSSSSMMMMMMMMWPTTTTZZZZOOOOOCOOOOOOOOOCO",
//            "HHHHHJJJJJSSSSSSSSSSYYYYYYYYYRRQRRRRRRRRUUUUBBBBBBBBBHHHEEEEEXXXXXXXZZZZZCCCCCCCCCCCCCHHHNNNRXXXXXSSSSSSSSMMMMMMWWPTTTTZMZZZOOCCCCOOOOOOOOOO",
//            "HHHHJJJJJJJSSSSSSSSSSYYYYYYYYRRRRRRRRRRRUUQUUBBBHHBBHHEEEEEEWXXXXXXXZZZZZCCCCCCCCCCCCCCCHPPNNXXXSSSSSSSSSSMMMMMMWWWTTTTTZZZZCCCCCCCCOOOOOUOU",
//            "HJJHJJJJJJJMSSSSSSSSSSYYYYYYYYRRRRRRRRRRRUQUUHHBHHBHHHHEEEWWWXXXXXXXZZZZZCCCCCCCCCCCCCYYCPPPPPSSSSSSSSSSSSMMMMMMWWMTTTTTZCCCCCCCCCCCOOUUUUUU",
//            "JJJJJJJJJJJJJSSSSSSSSSSYYYYYYYRRRRRRRRRRQQQQHHHHHHHHHHHEEEWWXXXXXXXXZZZZZCCCCCCCCCCCCCCCCPPPPPSSSSSSSSSSSMMMMMMMMMMMTTTTZCCCCCCCCCCCQCUUUUUU",
//            "JJJJJJJJJJJJJSSSSSSSIISYYYYYYYRRRRRRRRRRRPQQQHHHHHHHHHHEEHHWXXXXXXXXZZZZZKKNCCCCCCCCCCPPPPPPPPSSSSSSSSSSMMMMMMMMMMMMMTTTTCCCCCCCCCCCCCUUUUUU",
//            "JJJJJJJJJJJJJSSSSIIIIIIYYYYRRRRRRRRRRRRRRPPQPPHHHHHHHHHHEEHWXXXXXXXXZZZZKKKKKKCCCCCCCOPPPPPPPPPPSSSSSSSSMMMMMMMMMMMMMTTTTCCCCCCCCCCCCUUUUUUU",
//            "JJJJJJJJJJJPPPIIIIIIIIYYIIIRRRRRRRRRRRRCCPPPPHHHHHHHHHHHHHHHXXXXXXXXZZKKKKWKKKKCCCCCPPPPPPPPPPPASSSSSSSSSKMMMMMMMMMMMTTTTTCMCCCCCCCCCUUUUUUU",
//            "JJJJJJJJJJJQIIIAAAAAAAAIIEEEREBRRRRRRRRCCPCPCYHHHHHHHHHHHHHHXXXZQZZZZZKCCKKKKKKKKKCQQQQQQQQPPPPSSSSSSSSSMMMMMMMMUMMHHTTTTTTMMCHCCCFCUUUUUUUU",
//            "JJJJJJAAAAAAAAAAAAAAAAAAAAAARRBRRRRRRCCCCCCCCYHHHHHZHHHHHHHSXXXZZZZZZZKCCKKKKKKKKKWQQQQQQQQPPPPPSSSSSSSSSSMMMMMMMHHHHTTTTTTMMCHCCCUUUUUUUUUY",
//            "QJJJJJAAAAAAAAAAAAAAAAAAAAAABBBBBBBRRRRCCCCCBHHHZZHZZHHHHHMSXXXSZZZZZCCCKKKKKSKKWKWQQQQQQQQPCCPSSSSSSSSSSSMMHHHMHHHHHTTHTTTMHHHCFCUUUUUUUUUY",
//            "QJJJJJAAAAAAAAAAAAAAAAAAAAAABBBBBBBBRRRRCCCEBEHHZZZZHHHHHHMSXXXSSZZZCCCCCKKKKKKWWWWQQQQQQQQGCCCCSSSSSSSSSSHHHHHHHHHSSSTHTVVMHHUUFFFUUUUUYUUY",
//            "AAAAAAAAAAAAAAAAAAAAAAAACCBBBBBBBBBBRRRCCCCEEEEZZZZZHHHHHHMSXXXSSSZSSCCCCKKKKKKWWWWQQQQQQQQCCCCCCCESSSSSSSSHHHHHHHHSSSHHHHVVUUUUUFUUUUUYYUYY",
//            "AAAAAAAAAAAAAAAAAAAAAAAACCBBBBBBBBBBBRRRDCSBEBEEEZZZZZHHHHMSXXXSSSSSSSSCCKOKWKWWWWWQQQQQQQQQQQQCCEEEESVSSEHHHHHHHHHSSHHHHHVVUUUUUUUUUUUUYYYY",
//            "AAAAAAAAAAAAAAAAAAAAAAAACBBBBBBBBBBBBBRRDDBBBBBEEEXXZZHMMMMMSPPPSSSSWWWKKKKKWWWWWWQQQQQQQQQQQQQCEEEEEEEEEEHHHPHHHHHHHHHHHVVUUUUUUUUUUUUUYYYY",
//            "AAAAAAAAGGGGGGAAAAAAAAAABBBBBBBBBBTBTBDDDDBBBBBBBEHHHHHMPPPPPPPPSSSWWWWKWKKWWWWWWQQQQQQQQQQQQQQEEEEEEEEEEEHHHHHHHHHHHHHHHVVVVUUUUUUUUUUUYYYY",
//            "AAAAAAAAGGGGGGAAAAAAAAAABBBBBBBTTBTTTMDDDDBBBBBBBBHHHHMMPPPPPPPPPPPPPPWWWWWWWWWWWQQQQQQQQQQQQQQEEEEEEEEEEEEHHHHHHHHHHHHHVVVVVUUUUUUUUUHHYYYY",
//            "GGGGGGGGGGGGGGAAAAAAAAAAZBBBBBBTTBTTTTTDDDBRBBBBBBHHHMMMPPPPPPPPPPPPPPWWWWWWWWWCWQQQQQQQQQQQQQQPPPPEPPPEEEEXHHHHHHHUHVVHVVVVVVUUUUUUHHHHHHHY",
//            "GGGGGGGGGGGGGGAAAZZZZZZZZBBBTTTTTBTTTTTDDDDBBBBBBBHHHMMJPPPPPPPPPPPPPPKWWKKWWWCCCQQQQQQQQQQQQQQPPPPPPXXXXXEXXIXXXHUUVVVVVVVVVVUUUUUUUHHHHHHH",
//            "GGGGGGGGGGGGAAAAAZZZZZZZZBBBTTTTTTTTTTTTTDDBBBBBBBHHHHMJPPPPPPPPKKKKKKKWKKKKWWCCCQQQQQQQQQQQQQQPPPPPPXXXXXXXXXXXUUUUVVVVJJVVVVVVVUVUUHHHHHHH",
//            "GGGGGGGGGGGGAAAAAAAZZZZZZZRRRTTTTTTTTTTTLBBBBBBBBBBBMMMJPPPPPPPPKKKKKKKKKKCCCCCCCQQQQQQQQQQQQQQQQQQPPXXXXXXXXXXXXUUUUUVJJJJJJVJVVVVVVHHHHHHH",
//            "YYGGGGGGGGGGAAAAAAAZZZZZZZZRRTTTTTTTTTQTLBBBBBBBBBBMMMMJPPPPPPPPPKKKKKKKKKCCCCCCCQQQQQQQQBBQQQQQQQQPPXXXXXXXXXYXXUUUUJVJJJJJJJJVVVVVHHHHHHHH",
//            "YYGGHGGGGGGGAAAAAAZZZZZZZRRRTTTTTTTTTTQQBBBBBBBBBBBBBBMJPPPPPPPPPKKKKKKKKKCCCCCCCQQQQQQQQBBQQQQQQQQPPPXXXXXXXXXUUUUUUJPJJJJJJJVVVVVVVHHHHHHH",
//            "YYPGHGGGGGGHADDAAAWZZZZZZZZRRTTTTTTTTTQQBBBBBBBBBBBBEEMJPPPPPPPPPKKKKKKKKKCCCCCCCQQQQQQQQBBGGGPPPPPPPPXXXXXXXXXUUUUUUJJJJJJJJJVVVVVHHHHHHHHH",
//            "PPPPHHHHGGGHHHMAAAAZZZZZHHHTTTTTTTTTTTQQBBBBBBBBBBOBOEMJJJJJJJKKKKKKKKKKIICCCCCCCCCCCCCBBBBGGGGHPPPPPXXXXXXXXXXUUUUUJJJJJJJJJCJJVVVVHHHHHHHH",
//            "PPHHHHHHHGGHMMMMMMMZZZHHHHHTTTTTTTTTTTTTTTBBBBBBBOOOOOWJJJJJJJJJJJJJJKKKIICCCCCCCCCCCCCBBBBGGGGGWLLLLXXXXXXXXXXUUUJJJJJJJJJJTJJJJVUUUHHHHHHH",
//            "HHHHHHHHHHHHMMMMMMMMMZHHHHHHTTTTTTTTTTTTTEBBBBBBBBBOOOWJJJJJJJJJJJJCCCCCCCCCCCCCHCCCCCCBBBBGGGSLLLLLLXXXXXXXXXXXUUUUUJHHJJJJJJJJJJUUUUHHHHHH",
//            "HHHHHHHHHHHHSMMMMMMMMZHHHHHHHHTTTTTTTTEEEEEEBBBBBBBBOOWJJJJJJJJJJJJCCCCCCCCCCCCCCCCICCVBBBBLLLLKKKKKKKKKKKKKKKUUUUULLLHHJJJJJJJJUUUUUUHHHHHH",
//            "HHHHHHHHXHDHSMMMMMMMMMMHHHHUHTTTTTTTTTEEEEEEHHDBBBBDOOLWLLLLJJJJJJJCCCCCCCCCCCCCICCIMHHBBBBKLLLKKKKKKKKKKKKKKKXXULUULLJJJJJJJJJUUUUUUUUHHHHH",
//            "HXXXHHHHHHHHMZMMMMMMMMMHUUUUUWTTTTTTTTEEEHEEHDDBBDDDOLLLLLLLJJJJJJJCCCCCCCCCCCCIIIIIIKKBBBBKLLLKKKKKKKKKKKKKKKXILLLLLLLJJJJJJJUUUUUUUUUUUHHH",
//            "HHXQXXXXHHQQMMMMMMMMMMUHUUUUUWBTTTTTNBBEHHHHHDDDDDDDLLLLLLLLJJJJJJJCCCCCCCCCCCIIIIIIIKKKKLLLLLLKKKKKKKKKKKKKKKXIILIILLIJJJJJJUUUUUWWWUUUHHHH",
//            "HXXXXXNNHHQQQMMMMMMMMUUUUUUUUBBTTBBBBBBEEHHHHDDDDDSDLLLLLLLLJJJJJJJCCCCCCCCCCCIIIIIIIIKKLLLLLLLKKKKKKKKKKKKKKKXIIIIIIIIIJJJJJUUUUUWWWWWWWWWH",
//            "XXXXXXXNNNXQCCCCCMMMDUUBUUUUUUBBBBBBBBBEEHHHHHHHSDSDDDDLDLLCJJJJJJJCCCCCCCCCCCJIIIIIIIIKKKKLLLLKKKKKKKKKSUXIIIIIIIIIIIIIJJJJJJUUUWWWWWWWWWWH",
//            "XXXXXXXXXXXXCCCCCCCDDUUUUUUUUUBBBBBBBBBBEHHHHHHHSSSSDSSSDDNNJJJJJJJCCCCCCCCCCCJIIIIIIIIIKKKLLLLKKKKKKKKKRSIIIIIIIIIIIIIIIIJJJJUUUWWWWWWWWWHH",
//            "XXXXXXXXXXXXCCCCCCCIDUUUUUUUUUUBBBBBBBBBBDDHHHHSSSSSSSSSSDDDNNNNNNNCCCCCCCCCCCJIIIIIIIHIIKLLLLLLSSSSSSSSSSIIIIIIIIIIIIIIIDDJJDDUUUWWWWWWWWHH",
//            "XXXXXXXXXXXXOCCCCCCIDUUUUUUUUUUBBBBTTBBBBDDSSHSSSSSSSSSSSSSNNNNNNNNNCCCCCCCCCCJJJJIIIHHHHLLLLLLSSSSSSSSSSSIIIIIIIIIIIIIDIIDJJDDDUUWWWWWWWWWW",
//            "XXXXXXXXXXXXOOHHHHHIIIIUUUUUUUUUBBBNTBNBDDSSSSSSSSSSSSSSSPPPNNNNNNNNCCCCCCCCCCJJJHHHHHHHHLLLLLLSSSSSSSSSSSSIIIIIIIIIIIIDDIDDDDDDDDDWWWWWWWWW",
//            "XXXXXXXDXXXXXOHAHHHHIIUUUUUUUUUUBBBNNNNNSSSSSSSSSSSSSSSPPPPPNNNNNNNNCCCCCCCCCCJJJHHHHHHHHLLLLLLSKSSSSSSSSSSIIIIIIIIIIIIIDDDDDDDDDDWWWWWWWWWW",
//            "XXKXXXXDDXXOOOHHHHQHWIIUUUUUUUUUUGGGNNNNNNNSSSSSSSSSSQHQPPQQQNNNNNNNCCCCCCCCCCJJJJHHHHHHHHHLLLLLSSSSSSSSSIIIIININIIIIIIDDDDDDDDDDDDWWWWWWWWW",
//            "NXXTXXTTTXXOOOHHHHHHHIIUUUUUUUUUUGEGNNNNNNNSSSSSSSSSSQQQQPQQQQQQNNNNCCCCCCCJJJJJCJHHHHHHHLHLLLLLVVSSSSSSSIIIINNNNIIIIIIDDDDDDDDDDDDWWWWWWWWW",
//            "XXTTTTTTTTOOOOHHHHHHHIIIUUUWMUUUUJGGNNNNNNPPSSPSSSSSQQQQQQQQQQQQNNNNNNNJJJJJJJJJJJHHHHLLLLLLLLLLVVSSSSSYYYINNNNNNICIIIIDDDDDDDDDDDWWWWWWWWWW",
//            "TXTTTTTTTTTOFFFHHHHIIIIIUWWWWWWUWGGGNNNNNNPPSPPPSSSSQQQQQQQQQQQQQNNNNNNJJJJJJJJJJJHHHHLLLHLLLLLLSSSSSSSSSYNNNNNNNCCCCICDDQQQQPDDDDYWWWWWWWWW",
//            "TXTTTTTTTTTOIJFFHHHIIIIIWWWWWWWWWWWGWNNNPPPPPPPPSSSQQQQQQQQQQQQQNNNNNNNNJJJJJJJJJJJJHHHHLHHHLLHYYYSSSSSYYYNNNNNCCCCCCCCQQQQQQQDDDDDWWWWWWWWS",
//            "TTTTTTTTTTTTIFFFIHIIIIWWWWWWWWWWWWWWWNUPPPPPPPPPSSSQQQQQQQQQQQQNNNRNNNNNJJJJJJJJJJJHHHHHHHHHHLHYYYSSYSSYYYYYNNNCCCCCCCCCQQQQQQDDDIIWWWWWWWWS",
//            "TTTTTTTTTTTTIIIIIIIIIWWWWWWWWWWWWWWHHHUPPPPZPPPPPSSQQQQQQQQQQQQNNRRNRRRRFFFFJFFJJHHHHHHHHHHHHHHHYYYYYYYYYYYYYNNCCCCCCCQQQQQQQDDIIIIWJWWWXWWW",
//            "TTTTTTTTTTTTIIIIIIIIIWWWWWWWWWWWWWHHHHUPPPPPPPPPPPPPLLQQQQQQQQQQRRRRRRRRFFFFFFFFHHHHHHHHHHHHHHHHHYYYYYYYYYYYAANDCCCCCCCQQQQIIIIIIIIWJWWWXWWW",
//            "TTTTTTTTTTTTIIIIIIMMIUWWWWWWWWWWWWHHHHUPPPPPPPPPPPPPQQQQQQQQQQAARRRRRRRRRFFFFFHHHHHHHZZHHHHHHYYYYYYYYYYYYYYYAAAAACCCCCCCCHYYIYIITIIWWWIWWWRQ",
//            "TTTTTTTTTTTTTIIIIIMYWWWWWWWWWWWHHHHHHHHPPPPPPPPPPPPPQQQQQQQQQQAQRRRRRRRRRRFFHHHHHHHHZZZZHHHHHYEEYEYYYYYYYYAAAAAACCCCCCCCCCCYIYIITTIIIIIWIIRQ",
//            "TTTTTTTTTTTTBIIIIIMMMMWWWWWWWWWWHHHHHHHHZPPPPPPPPPOOQQQQQQQQQQQQTRRRRRRRRRRRHHHHHHRZZZZZZPHHHYEEEEEYYYYYYYYYAAAACCZOOCCCCCCYYYIITIIIIIIIIRRQ",
//            "TTTTTXXXBTVVJIIIIIMMMWWWWWWWWWWHHHHHHHHHPPPPPPPPPPPOQQQQQQQQQQQQTTRRRRRRRRHHHHHHHZZZZZZZPPEEEEEEEEYYYYYYYYYAAAAZZZZOOOOCCCCCTTTTTTTTTIIIIIRQ",
//            "TTTTXXXXXXJVJJIIIMMMWWWWWWWWWWHHHHHHHNHHPPPPPPPPPPPOOOOOQOQQQQQOOTORRRRRRRRRHHHHZZZZZZZZEEEEEEEEEYYYYYYYYYYYYAAZEZZZOOOOCCCCCTTTTTTTTTTTTTRR",
//            "TTTXXXXXJJJVJJIIIIMVVVWWWWWWWHHHHHHHHHHHOPPPPPPPPOPOOOOOOOOQQOOOOOORRRRRRRHHHHHHHZZZZZZZYEEEEEEEYYYYYYYYYYYYYKAEEZZZOOOOOOIITTTTTTTTTTTTTTRR",
//            "TXXXXXXYYJJJJIIIIIIVVVWWWWWWWHHHHHHHHHHHOPPOPPOPOOOOOOOOOOQQQOOOOOORRRRRHHHHHHHHHZZZZZZYYEEEEEEEEEIYYYYYYYYYYKKTEEEEOOOOOOITTTTTTTTTTTTRRRRR",
//            "TXXXXXXXYJJJJJIJIIIVVVVWWWWWWHHHHHHHHHHOOOOOPOOOOOOOOOOOOOOQOOOOOOORRRRRHRHHHHHHHHHZZZZYYYYEEEEEEEYYYYYYYYYOOKKKEEOOOOOOOOITTTTTTTTTTTTRRRRR",
//            "TXTXXXXXYYJJJJJJVVVVVVWWWWWWWWHHHHHHHHHHOOOOOOOOOOOOOOOOOOQQOOOOOOORRRRRRRHHHHHHHHHHHHZYYYEEEEEEEYYYYYYYYYYOOOOOOOOOOOOOOOIITTTTTTTTTTRRRRRR",
//            "TTTXXXXXXXJJJJJVVVVVVVVVWWWWWWHFFFFFFFHHHOOOOOOOOOOOOOOOOOOQOOOOOQORRRRRRRHHHHHHHHHHHHHHYYEEEMEEMMYYYYYYYYYYOOOOOOOOOOOOOOIIITTTTTTTTRRRRRRR",
//            "TTTXXXXXXZZZJJJVVVVVVVVVWWWWWWFFFFFFFHHLOOOOOOOOOOOOOOOOOOOOOOOOOOORRRRRRRHHHHHHHHHHHHHHYYEEMMMMMYYYYYYYYYYOOOOOOOOOOOQOIIIIITTFFTTRRRRRRRRR",
//
//)
//
//val realInput12gmail = arrayListOf(
//    "EEEEEEEEUUURRRRNRMMOJOOOOSSSSSSSSSSSSSEERRWWOOOOOOOOOOTTTTTCCCCCCRRYYYYYGGGGGGGGGGGGAAAAAAAAAAAAAPPPPMMMUUUUUUUUUURRRRRRRRRRRCCCCCCCHHHHHHHH",
//            "EEEEEEEEEURRRRRRRMROOOOOOSSSSSSESEEEEEEEEEWWWOOOOOOTTTTTTTTCCCCCCYYYYYYYGGGGGGGGGGGGAAAAAAAAAAAAAAAAPMMMMUUUUUUUUURRRRRRRRRCRCCCCCCHHCHHHHHH",
//            "EEEEEEEEEEUURRRRRRROOOOOOOOOSSEEEEEEEEEEEWWWWOWOOWOOTTTTTTTCCCCCCYYYYYGGGGGGGGGGGGGGAAAAAAAAAAAAPAAPPMMMMMMUMUUUUUURRRRRRCCCCCCCCCCCCCHHHHHH",
//            "EEEEEEEEEEUURRRRROOOOOOYYOOSSEEEEEEEEEEEDWWWWWWWWWOOTTTTTTTCCCCCYYUYGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPMBMMMMMMMUUUUUURRRRRRCCCCCCCCCCCCHHHHHH",
//            "EEEEEEEEEUUURRROOOOOOOOOOOOSSEEEEEEEEEEEWWWWWWWWWWOWWQTTTCCCCCCCCYUGGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPPBBMMMIMMUUUULLRRRRRRRCCCCCCCCCCCCHHHHH",
//            "EEEEEEEEEUUUEROOOOOOOOOOOFFEEEEEEEEEEEWWWWRWWWWWWWWWWWTTTTTSCCCCCCCGGGGGGGGGGGGGGGAAAAAAAAAAAAAPPPPPPPPPPMPPPPPCCLLLLLRAAAACCCAAACCCCCCCHHHH",
//            "EEEEEEEEEEEEERRRRRROOOOOOOFEEEHEEEEEEEWWWWWWWWWWWWWWWWWTTHSSCSCCCCCCGGGGGGGGGGGGGGAAAQQAAAAAAAAAAPPPPPPPPPPPPPPPCCLLLLAAAAAAAAAAACCCCHHHHHHH",
//            "EEEEEEEEEEEERRRRRRROOOOOOFFFFEHEEEEEEEEWWGWWWWWWWWWWWWWWOSSSCSSSCWWWWWGGGGGGGGGGGGGAXQQQQQQAQQAAPPPPPPPPPPPPPPPPCCLLLLLLAAAAAAAAACCCCHHHHHHH",
//            "RRRREREEEEEEERRRROOOOOOOOFFFFFEEEEEEEEEAAWWWWWWWWWWWWWWWSSSSCSSSSSSWWWWGGGGGGGGGGXXXXQQQQQQQQQAQQQOPPPPPPPPPPPPPPCLOLLLLLAAAAAAAAALLAHHHHHHH",
//            "RRRRRREESEERRRRRRRROOCOOOFFHHHAEEEEEEEAAAWWWWWWWWWWWWWSSSSSSSSSSSSKWWKWKGGGGXXGGGXXXZQQQQQQQQQQQQPPPPPPPPPPPPPPPPCCLLLLLAAAAAAAAAAAAAHHHHHHH",
//            "KRRRRGSSSSRRLLRRRRROOOOYOFHHHHHIEFEEEEEARJWWRWWWWQWDDDDSSSSSSSSPKHKWWKKKKGGGGXXXGXXXQQQQQQQQQQQQQQHPPPPPPMPPMMPCCCCLLLLLAAAAAAAAAAAAAAAHHHHH",
//            "RRRRRRSSSLLLLLRRRROOOOOYOOORHHHHEEEXXHHRRRRRRWWWWWDDDDDSSSSSSSSSKKKKKKKKQGQGQXXXGXXXXQQQQQQQQQQQQQQAQPPPMMPPMMMMMCCLLLLLLAAAAAAAAAAAAAAHHHHH",
//            "RCCSRRSSSSSLRRRRRROOOOOOOPOHHHHHHHHXXXHRRRRRRRWWWWDDDDDSSSSISSSQKKKKKKKKQQQQQXXXXXXXXXQQQQQQQQQQQQQQQPPPMMMMMMMMCCCCWLLLAAAAAAAAAAAAAAHHHHHH",
//            "RRRSSSSSSSSSSSSROOOOOOOOOOOHHHHHHHHXXHHRRRRRRRWDDDDDDDDSIIIIIIYQKKKYYYYKYQQQQXXXXXXXKKQQQQQQQQQQQQQQPPPMMMMMMMMMCCWWWWWWWAAAAAAAAAAAHHHHHHHH",
//            "SRSSSSGGGGGGSSSSOOOOOOOOOOOOHHHHHHHHHHHHHCRRRRRDDDDDBBBBBIIIIIYYYVKYYYYKYYQYQXXXXXXXXKQQQQQQQQQQNNNPPPPMMMMMMMMMCCWWWWWWWWWWWAAAAAAAIIIHHHHI",
//            "SSSSSSSGGGGGSSSSOOOOOOOOOOOHHHHHHHHHHHHHCCRRRRRDDDBBBBFBBIIIIYYYYYKYYYYYYYYYQXXXXXXXXXXXXXQQQQQQQQQPPPMMMMMMMMMMWWWWWWWWWWWWWAAAAIIIIIHHHHII",
//            "SSSSSSSGGGGGSSSSOOOOOOOOOOOHHHHHHHOHHHHQQQRQRDDDDBBBBBBBBBBBBYYYYYYYYYYYYYYYXXXXXXXXXXXXXXQQQQQTTTTTMMMMMMMMMMMMWWWWWWWWWWWEEAIIAIIIIIIHHHII",
//            "SSSSSSSSGGGGSSSSSSOOOOOOOOOOHHOOOOOHHHQQQQQQQDDBBBBBBBBBBBBIBVYYYYYYYYYYYYYYJXXXXXXXXXXXXQQQQQQQMMTTMMMMMMMMMMMMMWWWWWWWWWWWEEIIAIIIIIIIIIII",
//            "SSSSSGGGGGGGSSSSSSSOOOOOOOOOOOOOOOOHXQQQQQQQDDDDBBBBBBBBBBBBBBBQYYYYYYYYYYYJJXXXXXXXXXXXXXQQQPPQMTTTMMMMMMMMMMMMMWWWWWWWWWCCCEIIIIIIIIIIIIII",
//            "SSSSSGGGGGGGSSSSSSSOOOOOOOOOOOOOOOOHQQQQQQQZZZDDBBBBBBBBBBBBBBQQYYYEYYYYYYYYYXXXXXXXXXXXXXNPPNPMMMMMMMMMMMMMMMMMMMMWWWWWWCCCCEBIIIIIIIIIIIII",
//            "SSSSSSSSGGGGSSSSSSSOOOOOWOOOOOOOOOOQQQQQQQZZZZZDBBBBBBBBBBBSBQQQYYYEYYYYYYYFFXXXXXXXXXMMXNNNNNNNNNMNNMMMMMMMMMSMMWWWWWEEEEEEEEBBIIIIIIIIIIII",
//            "SSSSSSSGGGGGGSSSSSOOOOWWWOOOOXOXXOOQQQQQQZZZZZZBBYBBBBBBBBBBBQQEEEEEMYYYIVVIFXXXXXXMMMMMMNNNNNNNNNNNNNNNMMMMMMMMWWWWWEEEEEEEEEEEDINIIIIIIIII",
//            "SSSSSSSGGGGSSSSSSSSOOJWWWWWWOXXXXQQQQQQQQQZZZZZBBBBBBBBBBBBBBBEEEEEEEYYYIIIIIIXLMMXMMMMMMNNNNNNNNNNNNNNNMMMMMMWWWWWWWEEEEEEEEEDDDIIIIIIIIIII",
//            "SSSSSSSSSSSSSSSSSSSSSJWWWWWWXXXXXXQQQQQQZQZZZZZZZBBBBBBBBBBBBBEEEEEEYYYIIIFIIILLMMXMMMMMMNNNNNNNNNNNNNNNUMMMMMWWWWWWWWEEEEEEEEEEDIIIIMMMMMII",
//            "SSSSSSSSSSSYYYSSSSSSSWWWWWWWWWXXXXQQQQQDZZZZZZZZBBBBBBBBBBBBWWEEEEEEEEEFIIFLLLLLLMMMMMMMMMMNNNNNNNNENNNNNMWWWWWWWWWWWWEEEEEEEEEDDDDMMMMMMMMI",
//            "SSSSSSSSSSSSYSSSSWSWWWWWWWWWWWWXXXXXQQQZZZZZZZZZZZBBBBBBBBBBWWWYYEEEEDEFIILLLLLLLLMLMMMMMMMMNNNNNNNEENNNNNWWWWWWWWWWWWEEEEEEEEEEDDDDMMMMMMMI",
//            "SSSSSSSSSYYYYSSSSWWWWWWWWWWWWWWWXXXXQQQXZZZXZZZZZZBBBBBBWWWWWYYYYYEEIIIIILLLLLLLLLLLLMMMMMMNNNNNNNNEJEJWLWWWWWWWWWWWWEEEEEEEEEEEDDMMMMMMMMMI",
//            "SSSSSSSSSQYYYYSSSWWWWWWWWWWWWWWWWXXXXQXXXXXXZZZZZZZZZZZWWWWWWWYYYYEIIIIIIUILLLLLLLLLMMMMMMMMNKNNHHNEEEEWWWWWAAWWWWWWREEEEEEEEEDDDDMMMMMMMMMM",
//            "SSSSSPSSSYYYYYYSSWWWWWWWWWWWWWWWWQXXXXXXXXXXXZZZZZZZZWWWWWWWWWWWYYYYIIIIIIILLLLLLLLLMMMMMMMMHHNHHHHEEEEEAAAAAAAAWWWRRRXXXEEEEEDDDDMMMMMMMMMM",
//            "SWMSSMSSGYYYYYYYSSWWWWWWWWWWLWWWQQQXXXXXXFZZZZZZZZZZZZZZWWWWWIIIIIIIIIIIIIILLLLLLLLMMMMMMMMHHHHHHEHEEEEEIAAAAAAAWWRRRRXXXXXXXMMMMMMMMMMMMMMM",
//            "MMMSMMMYYYYYYYYYYUWWWWWLLLLLLLLLQQQXXXXXXFZZZZZZZZZZZZZZWKWWWWIIIIIIIIIIIIILLLLLLLMMMMMMMMMHHHHHEEEEEEEEEAAAAAAAWWRRRRRRXXXXXXMMMMMMMMMMMMMM",
//            "MMMMMMMYYYYYYYYYYUUUWWWWRLLLUULLQQQXXXFFFFFZZZZZZZZZZZZZKKWWWWIIIIIIIIIIIIIIILLLLLLMMMMMMMMAAHHHEEEEEEEEEEXAAAAAWRRRRRRRXXXXXXXXMMMMMMMMMMMM",
//            "MMMMMMYYYYYYYYYYYYYYWWWLLLLLLLXXQQQXXXFFFFFFFFFZZZZZZZZZKKWWWIIIIIIIIIIIIIIIIIILJMLMMMMMMMMMAHHWEEEEEEEEEMMMAAAAARRRRRRIIXXXXXXMMMMMMMMMMMXX",
//            "MMMMMRYYYYYYYYYYYYYLWWLLLLLLLLXXQQXXXXXXFFFFFFFKKZZZZZZZKKWWWWIIIIIIIIIIIIIIIAALLMMMMMMMMMMMAAHMTEEEEEEEEMMMMDAAAARRRRIIIIIIXXXXMMMMMMMMMMMM",
//            "MMMMLYYYYYYYYYYYYYCCMWRRRLLLLXXXXXXXXXXXFFFFFFFFFZZZZZKKKKKKWIIIIIIIIIIUIVVIAAAAMMMMMMMMMMMMMMMMMEEEEEEEEMMMMMMMAAAARIIIIIIIXIIXXMMMMMMMMMME",
//            "MMMMLAAYYYYYYYBYCCCCCWRLLLLLXXHXXXHHXXXFFFFFFFFFZZZZZZKKKKKKIIIIIIIIIIIIVVVVVAAAMMMMMMMMMMMMMMMMMEEEEEEEMMMMMMMBBAAAAAAIIIIDIIIIIMMMMMMMMMME",
//            "PPMMAAAYYYYMAAAAACCCCCRCLMLMHHHXXXHHHXXFFFFFFFFFFFZZKTTTTTTTTTAIIIIIIIIVVVVVVAAAAAAMMMMMMMMMMMMMMEEEEEEEMMMMMMMBBBBAAAAAUXIIIIIIIMIIIMMMMMEE",
//            "FAAAAAAAYYYYAAAAACCCCCCCCMMMHHHHHHHHHHHFFFBFFFFFFKKKKTTTTTTTTTIIIIIIIIVVVVVVAAAAAAAAAAAMMMMMRMRMVVVEREEEMMMMMMMBBBAAAAUAUXXXXXXIIIIIIIGGMEEE",
//            "FAAAAAAAAKYYAAAAACCCCCCCCCCMMHHHHHHHHHHPFFFFFXQFTTKKKTTTTTTTTTIIIIIISSVVVVVVVVAAAAAAAHHMMMMMRRRREEEERERMMMMMMMMBBBBBBAUUUUUUUXXIIIIIIIIMMMEE",
//            "FFFAAAAAAAAAAAAACCCCCCCCCCCMHHHHHHHHHHHFFFFJXXTFTTTTTTTTTTTTTTIIIIIIIIIVVVVVVVAAAAAAAHHHHHHHHRRRRRRRRRRRMMMMMMMBBBBBBBUUUUUXXXXIIIIIIIIEEMEE",
//            "FFAAAAAAAOAAAAACCCCCCCCCCCCCHHHHHHHHHHHJFFFXXTTTTTTTTTTTTTTTTTIIIIIIIIIIVVVVVVAAAAHHHHHHHHHHHRRRHRRRRRRMMMMMMMMMBBBBBBBBUUUUIIIIIIIIIIIIEMEE",
//            "FFFFFAAAAFFAFXXXCCCCCCCCCCCCFFHHHHHHHHHHXXXXXXETTTFTTTTTTTTTTTTIIIIIIIIIVVVVVAAAAAAAHHHHHHHHHHRHHHRRYYYIKKMMMMMMBBBBBBBUUUUUUIIIIIIIIIIEEEEZ",
//            "FFFFFFFFFFFFFEEXECCCFCCCFFCCFFNHHHHHHHHHXXXXXXETTTTTKTTTTTTTTTTIIIIIIIIIVVVVVAAAAAAHHHHHHHHHHHHHHHHYYYKKKMMMMMUMMBBBBBUUUUUUUYIIIIIIIIIIEZZZ",
//            "FFFFFFFFFFFFFEEEEFFFFFCFFFFFFFHHHHHHHHHXXXXXXXXXTTTTTTTTTTTTTTTTTTIIIIIIVVVAVAAAAAAAHHGHHHHHHHHHHYYYYYNNNMMMMUUUBBBUBUUUUUUUUUIIIIIIIIIIIZZZ",
//            "FFFFFFFFFFFFFEEEEFFFFFFFFFFFFFYHHHHHHXXXXXXXXXXXTRRTTTTTTTTTTTTTTTTIIIIIVVVAAAAAAAWWWWWWWWWWHHHHHYYYYYYNNMMMMUUUUBUUUUUUUUUUXXIIIIIIIIIIIIIZ",
//            "FFFFFFFFFFFFFEEEEEFEEFFFFFFFFFFFHHHZHXXXXXXXXXXXRRRKKTTTTTTTTTTTTTTIAIAIIIIAAAAAAAWWWWWWWWWWHHHHHYYYYYYYYYYYYUUUUUUUUUUUUUUUXIIIIIIIIIIIIICE",
//            "FFFFFFFFFFFXFEEEEEEEEFFFFFFFFFFFHHZZXXXXXXXXXXXXRRKKKKKKTTTTTTTTTTTIAAAIIIAAAAAALLWWWWWWWWWWHHHHHYYYYYYCCCYYYYPUUUUUUUUUUUUUXXIIIIIIIIIIICCC",
//            "FFFFFFFFFFFFEEEEEEEEEFFFFFFFFFFFHHZXXXXXXXXXXXXXRRRKKKZZTTTTTTTTTTTITAAAAAAAAAAALLWWWWWWWWWWWWWHHYYYYYYCCCYYPYPUUUUUUUUUUUUUUXIIIIKIIIIIISCC",
//            "FFFFFFFFFFEEEEEEEEEESFFFFFFFFFFFFXXXXXXXXXXXXXXXRRRKKRUUUUUTTTTTTTTTTAAAAAAAAAAAALWWWWWWWWWWWWWWWYYYYYYCCCYYPPPUPPUUUUUUUUUUUKIIIIKIIIICSSCC",
//            "FFFFFFFFEEEEEEEEEEBFFFFFFFFFFFFFFFFXXXXXPXXXXXXXRRRKRRRUUUUTTTTTTTTTTTTAAAAAAAAALPLLLLLLWWWWWWWWWYYYYYYCCCYYYPPPPPUPUUUUKKKKKKKIIIIIRRRCCCCC",
//            "FFFXIFEEEEEEEEEEEBBPFFFFFFFFFFFFFFFFFXXXPXXXXFXXRRRRRRRUUUUTTTTTTTTTTTTAAAAAAAALLLLLLLLLWWWWWWWWWYYYYYYCCCCCCCPPPPPPUKKKKKKKKKKRRRIRRCCCCCCC",
//            "XFIIIIIIEEEEEEEEEBBPPPPPPPFPPFZFMMMMMSMLMNXXXXXQRRRRRRUUUUUTTTTTTTTTTTTTAAHHAAALLLLLLLLLWWWWWWWYYYYYYYYCCCCCCCPPPPPPUWWWKKKKKKQRRRRRRRRRCCCO",
//            "XXXQIIIIIEEEEEEEEEBPYPPPPMPPPZZMMMMMMMMMMMMXTTXQRRRRRRUUUUUUUUUUUUUTTHHHHHHHHALLLLLLLLLLWWWWWWWYYYYYYYYCCCCCCCPPPPPPWWKKKKKKKKKRRRRRRRRROCCO",
//            "XXIIIIIIIIIEEEEEEEEYPPPPMMPZZZZMMMMMWMMMMMMMTTTQQRRRRRRUUUUUUUUUUUUTHHHHHHHHHHMLLLLLLLLLWWWWWWWYYYCCCCCCCCCCCCPPPPPPPWWWWKKKKKKRRRRRRRROOOOO",
//            "IIIIIIIIIIIEEEEOOOOPPPPPPPPPZZZMMMMMMMMMMMMMMQQQQRRRRRRUUUUUUUUUUUTTTTHHHHHHHHMLLLLLLLLLFFFFYYYYYYCCCCCCCCCCCCPPPPPPPWWWWKKOORRRRRRRRRRROOOO",
//            "MIIIIIIIIIQEEEEPPPPIIIIIIIIIIZZMMMMMMMMMMMMMZZZQQRRRRRRUUUUUUUUUUUTTTHHHHHHHMMMMLLLLLLLFFFFFYYYYYYCCCCCCCCCCCCSSPPMMBBBBBOOOOORRJRRRRRRRROOO",
//            "MMIIIIIIIFFEEEEAAAAIIIIIIIIIIIIIIIIIIMMMMMQMRRZQQQQRRRRRUUUUUUUUUTTTTHHHHHMMMMMLLLKKLLLFFFFFYCCCCCCCCCCCCCCCCCSSSSSMMBBBBOOOOOORRRRRRRRROOOO",
//            "MMIIFIFPFFFEEEEEAAPIIIIIIIIIIIIIIIIIIMMMMMRRRQQQQQQQQRVRUUJUUUUUUTTTTHHHHHHMMMMMLJJKJQLLFFFFYYCFFFCCCCCCCCCCCCSSSSSBBBBBBOOOOORRRRRRORRROOOO",
//            "FFFFFFFFFFQQQEAAAAAIIIIIIIIIIIIIIIIIIMMMMMRRRRQQQQPPVVVVJJJJUUJUTTTTTTTHHHTTMMMJLJJJJFFFFFFFFFFFFNCCCCCCCCCCSSSSZZSSBBBBBOOOOOORRRAROOOOOOOO",
//            "FFFFFFFFQQQQQQUAAAAIIIIIIIIIIIIIIIIIIMMQMMMRRRRQQQPVVVVVJJJJJJJUTTTTTTTTHHTTMMMJJJJJJFFFFFFFFFFFFNCCCCCCCCCCCCCCZZZBBBBBBBOOOORRRRAROOOOOOOO",
//            "FFFFFFFFFQQQQQUAAAAIIIIIIIIIIIIIIIIIIMMQQRRRNRQQQPPPPVVVVJJJJJWTTTTTTTTTTTTTTLJJJJJJFFFFFFFFFFFFFSCCCCCCCCCCCCCCZMBBBBBBBBNNNNEERAAACOOOOOOO",
//            "FFFFFFFFFFFFQUUUAUUIIIIIIIIIIIIIIIIIIIIQQQQRQRQQQVVPVVVVVJJJJWWWTTTTTTTPTTTTTLJJJJJBBFFFFFFFFFFFFSCCCCCCCCCCCCCCZMMMBBBBBBBNNNNNNACCCOCCOOOO",
//            "FFFFFFFFFFFWUUUAAUUIIIIIIIIIIIIIIIIIIQQQQQQQQQQQQQVVVVVVVJJWWWWWWTTTTTPPTTTTTLJJJJLBLFFFFFFFFFFFSSSSSSSCCCCCCCCCMMMMBBBBBBBBNNNNAACCCCCCCCOO",
//            "FFFFFFFFFFFWUUUUUUUUUUUUUUPFFIIIIIIIIQQQQQQQQQQQQQVVVVVVVVJJWWWWWTTTPPPTTTTLLLLJLLLLLIFFFFFFFFFFFSSSSSACCCCCCCCCMMMMBBBBBTNNNNNNNACCCCCCCCCC",
//            "FFFFFFFFEFFWUUUUUUUUUUUUUUFFFIIIIIIIIQQQQQQQQQQQQVVVVVVVVVVWWWWWWWTTPPPLTTLLLLLLLLLLLLLFFDDFFFFSSSAASSACCCCCCCCCMMMMBBBBBTNNTNNNNNICCCCCCCCC",
//            "WFFFFFFFEFFEPPUUUUUUUUUUUUUFFFFFFMMMQQQQQQQQQQQQQVVVVVVVVVVVWWWWWTTWLLPLTTLLLLLLLLLLLLDFFDDFDFFSTSAASAACCCCCCCCCMMMMBBTBBTTTTVNNNIICCCCCCCCC",
//            "FFFFFFEEEEEEPPUUUUUUUUUUUUFFFFFFMMQQQQQQQQQQQQQQVVVVVVVVVVOVTWWWWWWWWLLLLLLLLLLLLLLLLDDDDDDDDFFSTAAAAACCACCCCCCCMKMMBBTTTTTTTTTIIICCCCCCCCCC",
//            "IIFFFEEEHEPPPPUUUUPUUUUUUUFFFFFFFFQQQFFFFFFFFFQQQVVVVVVVVVVVTWWWWWWWWWWLLLLLLLLLLLLLLLLDDDDDDTTTTTTAAAACACCCCCCCMBMKBTTTTTTTTTTIIIICCCCCCCCC",
//            "IIIFFFFEFPPPPPPUUUUUUUUUUUFFFFFFQQQQQFFFFFFFFFVQVVVVVVVVVVVVVWWWWWWWWLLLLLLLZLLLLLLLLLLDDDDDDDTXTTTTTTAAACCCCCCCBBBBBDTTTTTTTTTIIIICCCCCCCCC",
//            "IIYFFFFFFPPPPPPPPFFFFUUUUFFFFPFFQQNNNFFFFFFFFFVVVVVVVVVVRRRVVWWWWWWWWWLLLLLLZLLLLLLLDDDDDDTDTTTTTTTTTTTTACCCCCCCABBBBBTTTTTTTTIIIIIICCCCCCZZ",
//            "IIYFFFFFPPPPPPPPPFFFFXXUUFFPPPPPNNNNNFFFFFFFFFVVVVVVVVVVRRWVWWWWWWWWWWLLLLLLZLLZZZZDDDDDTTTTTTTTTTTTTTTTTCCCCCCCAAABAATTTTTTTIIIIIIICCCCCCZZ",
//            "IIYYFFFFFPPPPPPPPFFFFXXXUUXNPPPPNNNNNFFFFFFFFFZPVVVVVVVVRRWWWWWWWWWWTTLLLLLLZZZZZZZDDDDDTGTTTTTTTTTTTTTTTCCCCCCCAAAAATTTTTTTTIIIIIIICCCCCCZC",
//            "XRYYYYFPPPPPPPPPPFFFFXVXXXXNPPNNNNNNNFFFFFFFFFPPVVVVVVVVRRWWWWWWWWWWTTLLLLLZZZZZZZSSDDDDTTTTTTTTTTTTTTTTTCCCCCCCAAGJJTTTTTTTIIIIIIIICCCCCCCC",
//            "XRRRRYYPPPPPPPPPPFFFFFFFFFXNNNNMNNNNNFFFFFFFFFPPPVVVVVVVWWWWWWWWWTTTTTLLLLLLZZZZZZSSDSDDTHTTTTTTTTTTTTTTTTAAAAAAAAGJJTTTTTTIIIIIIIICCCCCCCCC",
//            "XXXRBRRPPPPPPPPPPFFFFFFFFFFFFFFFFFFNNFFFFFFFFFFFPVVVVVVVTWWWWWWWTTTTTTTTLLLLZZZZZZZSSSSSTTTTTTTTTTTTTTTTTTAAAXAGJGGGJGTTTGIIIIIIIIIIICCCCCCC",
//            "XXXRRRRPPPPPPPPPPFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFJJVEVTTTVTWWWWWWTTTTTTTTLLLLLDZZZZZZZSSSSSSTTTTTTTTTTTTTIIAAAXXGGJGGGGGXXGGIGIIIIIIIIICCCDDCC",
//            "XXXLRRXPPPXXPPPPPVVFFFFFFFFFFFFFFFFFFFFFFFFFFFJJJJETTTTTTTTWTTTTTTTTTTLLLLLLDZZZZZZZSSSSSSYLTTTTLLTTTTTTTAAXXXXGJGGGGGGXGGGGGIIIIIIDDDDDDDDD",
//            "XLXLLLXXXXXXXXPPVVVFFFFFFFRRNNNFFFFFFFFIIIIIJJJJJEEETTTTTTTTTTTTTTTTTTTTMLLWDDZZZZZZSYSYYYYLTTTTLLLLTTTVVXXXXXGGGGGGGGGXGGGGIIIIIIIDDDDDDDDD",
//            "XLLLLLLLXXXVXXPVVVVVVVVVVTERNNNFFFFFNNIIIIIJJJJJJJEETTTTTTTTTTTTTTTTTTTXMMLMRDZZZZZZYYYYYYYLLLLLLLLLLTVVNNNXXXXGGGGGGGGGGGGGIIIDIIDDDDDDDDDD",
//            "LLLLLLLLLXXVXXPVVVEEEVVEEEERRNNFFFFFNNIIIIIIJJJJIIIEETTTTTTTTTTTTTTTTTXXMMMMZZZZZZZZYYYYYYLLLLMLLLLLLLVVNNNXXGJGGGGGGGGGGGGGIDDDDDDDDDDDDDDD",
//            "LLLLLLLVVVVVVVVVVVVVEEVEEEERNNNFFFFFNIIIIIIIIIIIIIIIEEEBTTTTTTTTTTTTMXXXXMMMMZZZZZZZZYYYLLLLLMMLLLLLLLNNNNNXGGGGGGGGGGGGGGGLIDDDDDDDDDDDDDDD",
//            "LLLLLLLLVVVVVVVVVVVVVEEEEERRRRRRRNNLLLIIIIIIIIIIIIIIIEBBTTTTTTTTTTMMMXMMMMMMMZJZZYZZZZYYLLLLLLLLLLLLQLDNNNNXXGGCCGGGGGGGGGULLLDDDDDDDDDDDDDD",
//            "ALLLLLLVVVVVVVVVEVVVEEEEEHEERRERRNNLLLLLIIIIIIIIIIIIIFZBBSTTTTTTTTMMMMMPMMMMMZZZYYYZYYYYYLLLLLLLLLLQQQQQNNNCCCCCGGGGGGGGWGLLRNDRRRDDDDDDDDDD",
//            "LLLLLLLLLVVVVVVEEEEVVEEEEEEEEEERRRRLLLLLIIIIIIIIIIITTFFBBBTTTTTTMMMMMMMMMMMMVZEZYYYYYYYYLLLLLLLLLLLQQQQNNNNCCCCCGGGGGGLLWLLLRRRRRRRRDDDDDDDD",
//            "LLLLLLLLLLVVVVEEEEEEEEEEEEEEEEERRLLLLLLLLLIIIIIIIIIIIFFQQBBTTTTTMMMMMMMMMMMMMMEZYYYYYYYYYLLLLLLLLQQQQQQWWNNCCCCCGCCGCCLLLLLLRRRRRRRRRDDDDDDD",
//            "LLLLLLLLLLVVVVAAAEEEEEEEEEYEEEELLLLRRRRRRRIIIIIIIIIIIIFQQQQTTTTWWMWMMMMMMMMMMMMYYYYYYYYYYYLDEELLLQQQQQQQWWBCCCCCCCCCCCLLLLLLLRRRRRRRRDDDDDDD",
//            "LLLLLLLLLLVVVVAAAEEEEEEEEYYEYYLLLLLRRRRRRRLIIIIIIFFIFFFQQQLLTWWWWWWMMMMMMMMMMMMYYYYYYYYYYYYEEELLLQQQQPPQBWBCBCCCCCCCCCLLLLLLLLRRRRRRRRRRDDDD",
//            "LLLLLLLFLLVVMLAAAAEEEEEEEYYEYYLLLLLRRRRRRRLIIIIIIFFFFFFLLLLWWWWWWWWMMMMMMMMMMMMMYYYYYYYYYYYEEPLLLQQQQPBBBBBBBBCCCCCCCCCLLLLLLLRRRRRRRRRDDDDD",
//            "LLLFFFFFFLVLLLAAAEEEEEEEEEYYYYLLLLLRRRRRRRIIIIIIIFFFFFFLLLLLWWWWWWWMWMMMMMMMMMMMYYYYYYYYYYEEEPELLPPPQBBBBBBBBBCCCQQCCCLLLLLLLLLTTTLRLRRRRDDR",
//            "LLFYFFFFFLLLLAAAEEEEEEEEYYYYYYLLLLLRRRRRRRIIIIIIIFFFFFFFLLLLLWWWWWWWWWMMMMMQPMMMYYYQQYYYYYEEEEEPLPPPBBPBBBBBBBBCCQQQQCCLLLLLLLLLTTLLLLDDDDDD",
//            "FFFFFFFFFLLLAAAAJJEEEEEEEEYYYLLLLLLRRRRRRRUIIDIIIFFFFFLLLLLLLWWWWWWWWWWWMMPQQMMQQQQQQQYNNNEEEPPPLPPPPPPBBBBBBWQQQQQQQQLLLLLLLLLLTLLLLLLDDDDD",
//            "FFFFFFFFFLLLLAAAJJJJJEEEEEJYYYLLLLLRRRRRRRUUIULLIIFFFLLLLLLLLLWWWWWWWQQQQMPQMMMQQQQQQYYNNEEEENPPPPPPPPRCBBBBBQQQQQQQGQLLLLLLLLLLLLLLLLLLDDDQ",
//            "FFFFFFFFFFFLLAAAJJJJJJJJEJJYLLLLLLLRRRRRRRRRUUULFIFFFFLLLLLLLLWWWWWWWQQQQQQQQQQQQQQGGGNNNNEZNNPPPPPPPPRRRBBBQRQQQQQQQQQLLLLLLLLGLLLLLLLLDDQQ",
//            "FFFFFFFFFFFFAAAAJJJJJJJJEJJYYLLLRRRRRRRRRRRRUUUUFFFFFFLLLLLLLLLWAWWWWWQQQQQQGGGGGGGGGGNNNNENNNPPPPPRPPRRRRKBQQQQQQQQQQQQQLLLLLGGLLLLLLLLDQQQ",
//            "FFFFFFFFFFFFAAAAAAJJJJJJJJJYYLLLRRRRRRRRRRRRUUUFFFFPPFFPLLLLLLAAAWWWWWQQQQQQGGGGGGGGGGNNNNNNNNPPPPPRRPRRRRKKKKQQQQQQQQQQQLLLLGGGGGLLLLLLKQQQ",
//            "FFFFFFFFFFFFFFFAJJJJJJJJJJJJYLLLRRRRRRRRRRRRUUUFFFFPPPPPLLLLLLAAAAWWWCQCCQQQGGGGGGGGGGNNNNNNNNNNPPPRRRRRRRKKKQQQQQQQQQQQLLGLLGGGGGLLLKKKKQKQ",
//            "FFFFFFFFFFFFFFFFJJJJJJJJJJJJYYYLRRRRRRRRRRRRGUFFFFPPPPPPALLAAAAAACCCWCCCCCQCGGGGGGGGGGNNNNNNNNNNPPRRRRRRRRKKKQQQQQQQQQQQQGGGGGGGGGLLKKKKKKKK",
//            "FFFFFFFFFFFFFFLFJJJZZJJJJJJJJYYJRRRRRRRRRRRRUUFFPPPPPPPPPQAAAAAAAACCCCCCCCCCGGGGGGGGNNNNNNNNNNNKNRRRRRRRRKKKKKQQQQQQQQQQGGGGGGGGGGGLLKKKKKKK",
//            "FFWFFFFFFFFFFLLLLJJJZJJJJJJJJYYJRRRRRRRRRRRRSSFFPPPPPXXXXXXQQAAACCCCCCCCCCCCGGGGGGGGNENNNNNNNNNNNRRRRRRRKKKKKKKKQQQQQSGQGGGGGGGGGGGKKKKKKKKK",
//            "FWWFFFFFFFFFHLLLLHBBJJJJJJJJYYJJRRRRRRRRXXXXXPPYPPPPPXXXXXXXXXXXUUACCCCCCCCCCCCGGGGGQEEENNNNNDWNERRRRRKKKKKKKKKKKKQQSSGGGGGGGGGGGGKKBKKKKKKK",
//            "WWFFFWWWHFFHHHHHHHJJJJJJJJJJJJJJJJJJJJJRXXXXXPPPPPPPPXXXXXXXXXXXUUACCCCCCCCCCCCGGGGGEEEENNNNNWWPEEERRRKKKKKWWKKKKKQQQQGGGGGGGGGGGGKKKKKKKKKK",
//            "WWOOWOWWHHHHHHHHHGGGGJJJJJJJJDJJJJJJJJJJXXXXXWPPPPPPPPXXXXXXXXXXUUCCCCCCCCCCCCCGGGGGEEEEEENNHHWWEEEKKKKKKKWWWWKJJJJJJJGGGGGGGGGGGGKKKKKKKKKK",
//            "WWWOOOOHHAHKHHHHHHGGJJJGJJDDDDJJJJJJJJJJXXXXXPPPPPPPUUXXXXXXXXXXUUCCCCCCCCCCCCRGGGGGEEEEEEWWWWWHHEEEEEKKKKWWWWWJJJJJJJGGGGGGGGGGGGKKKKKKKKKK",
//            "WWWOOOOOHHHHHHHHHHGGGGGGGGDDDJJJJJJJVVJJXXXXXXXXXXXXXXXXXXXXXXXXUUCCCCCCCCCRRRRRRRRREEEEEWWWWWWHHEEEEEKEEEWWWWWWJJJJJJJJGGGGGGGGGGGKKKKKKKKK",
//            "OOOOOOOOOOHHHHHHHHHHGGGGGGGDDJDJDJJJVVJVXXXXXXXXXXXXXXXXXXXXXUUUUUAAACCCCCRRRRRRRRRREEEEEWWWWWWWHHEEEEKEEWWWWWWYJJJJJJJJGGGGGGVVGVVLKBKKKKKK",
//            "ROOOOOOOOOHHHHHHHHHHGGGGGGGGDDDDJJJJJVVVXXXXXXXXXXXXXXXXXXXXXUUUUUACCCCCCRRRRRRRRRRRRREEWWWWWWWWWEEEEEKEEWWWWWWYYJJJJJJJGGGGGVVVVVVVVKKKKKKK",
//            "RROOOOOOOOHHHHHHHHHHHGGGDDGGDDDDDDDJVVVVVVVVXXXXXXXXXXXXXXXXXUUUUUACCCCCCCRRRRRRRRRVVVDEWWWWWWWWEEEEEEKEEKKWWSSJJJJJJJJGGGGGGVVVVVVVVKKKKKKK",
//            "RROOOOOOOOHHHHHHHHHHXGXGDDDDDDDDDDDDVVVVVVVVXXXXXXXXXXXXXXXXXUUUUUCCCCCCCCCCRRRRRRRVVVDEEWWEEEEEEEEEEEEEEKKWWSSJJJJJJJJJJGGJVVVVVVVVVVYKKKKK",
//            "ROOOOOOOOOOHHHHHHOHXXXXXUDDDDDDDDDDDDVVVVVVVXXXXXXXXXXXXXXXXXAAAACCCCCCNCMMRRRRCCRVVVDDDEWWEEEEEEEEEEEEEEEESSSSJJJSJJJJJGGJJVVVVVVVVVKKKKKKK",
//            "OOOOOOOOOOOHHHOHOOOUUUUUUDDDDDDDDDDDDVVVVVVVXXXXXXXXXXXXXXXXXAAAAAAAACNNNRRRRRRICCVVVVDEEEEEEEEEEEEEEEEAAEEESSSSSSSSSJJJJJJJBGVVVVVVVKKKKKKK",
//            "OOOOOOOOOOOOHHOOOOOUUUUUUUDDDDDDDDDDVVVVVVVVXXXXXXXXXXXXXXXXXAAAAAAAAAANNNNRCCCCCCVVVDDDEEEEEEEEEEEEEEEESSSSSSSSSSSSSJJJJJJJBBBSSSVVVKKKKKKK",
//            "OOOOOOOOOOOOHOOOOUUUUUUUUUUDDDDDDDDDVZVVVVVVVVYHXXXXXXXXXXXXXRRRAAAAAAANNNZCCCCCCCDDDDDDDEEEEEEEEEEEEEEESSSSSSSSSSSSSJJJJGJJBBBBSGKKKKKKKKKK",
//            "OQOOOOOOOOOOOOOOOUUUUUUUUUUDDDDDDDDDVVVVVVVVVVVYXXXXXXXXXXXXXRRRRRAAAAZNNZZCCCCCCVDDDDDDDDDEEWEEEEEEEEEAAAASSSSSSSSSSJJJJGJGGGBGGGKKYKKKKKKK",
//            "MQOOOOOOOOOOOOOOOUNNUUUUUUUUUUDDDDDDVVVVVVVVVVVVXXXXXXXDRRRRRRRRRIZZAZZZZZZZCCCCVVVDDDDDDDEEEWEWEEEEEEEKAAASSSSSSSSSSSJJGGGGGGGGGGYYYKKKKKKK",
//            "QQOOQQOOOOOOOOOOONNNUUUUUUUUUDDDVDDDDDVVVVVVVVDDXXXXXXXDRRRRRRRRRIZZZZZZZZZCCCCCCVDDDDDDDDZZWWWWWWWEEEOKAAASSSSSSSSSJJJGGGGGGGGGGYYYYKKKKYYK",
//            "QQOQQQOOQOOOOOOOOVUUUUUUUUUUUVDDVDDDDDDDVVVVVVVVXXXXXXDDRRRRRRRROZZZZZZZZZZZCCCVVVDDDZZDZZZZWWWWWWWWWOOOOAAASSSSSSSJJGGGGGGGGGGGZYYYYYKYYYKK",
//            "QQQQQQOQQQOOOOOVVVEVIIUJJUUUUVVVVDZDDDDDVVVVVYYDDDDDDDDDRRRRRRRRZZZZZZZZZZZZZNCOOOOZZZZZZZZZWWWWWWWWWWOOOAAOSOSSSSSSGGGGGGGGGGGGYYQYYYYYYYYY",
//            "QQQQQQQQQQKQQQOOVVVVVVJJJJJJVVVVVDDDDDDVVVVVYYYDDDDDDDDDQRARRRRZZZZZZZZZZZZKKKKKKKKZZZZZZZZZWWWWWWOOOWWOOOOOOOSSSSOOGGGGGGGGGGGGYYYYYYYYYYYY",
//            "QQQQQQQQQQQQQQOOOVVVVJJJJJJJJVVVVDDDDDDDVVVYYYJDDDDDDDDDDRRRRRRRRZZZZZZKKKKKKKKKKKKZZZZZZZZWWWOWWWOOLWWOOOOOOOSOOSOOGGGGGGGGGGGGGYYYYYYYYYYY",
//            "QQQQQQQQQQQQOOOOOOOVOOJJJJJVVVVVVVDDDDDDDVOJJJJAADYYDMDDDRRRRRRRRZZZZZZKKKKKKKKKKKKKKKKZZZZWWWOOWOOOOOOOOOOOOOSOOSOOGGGGGGGGGGGGGYYYYYYYYYYY",
//            "QQQQQQQQQQOQOOOOOOOOOJJJJJJVVVVVVVVVDDDDDDJJJJJJJJYYDMMMMRRRRRYYYZZZZZZKKKKKKKKKKKKKKKKZZZWWOOOOOOOOOOOOBOOOOOOOOOOOGGGGGGGGGGGGGGYYYYYYYYYY",
//            "QQQQQQQQWOOOOOOOOOOOOJJJJJVVVVVVVVVDDDDDJJJJJJJJJJMMDDMMMMRMRMYYYZZZZAAKKKKKKKKKKKKKKKKZWWWWOOOOOOOOOOOOOOOOOOOOOOOGGGGGGGGGGGGGGGYYYYYYYYYY",
//            "QQQQQQQQWOWOOOOOOOOOOJJJJJVVVVVVVDDDDDDDDDJJJJJJJJMMMMMMMMMMMMYYAAAAAAAKKKKKKKKKKKKKKKKWWWWWOOOOOOOOOOOOOOOOOOOOOOOOGGGGGGGGGGGGGGYYYYYYYYYY",
//            "QQQQQQQQWWWWWOOOOVOOOOOOJXOVVVVVVDDLDDDDDDDJJJJJJJJMMMMMMMMMMMMMIAAAAAAKKKKKRRRKKKKZZCZWWWWWOOOOOOOOOOOOOOOOOOOOOOOORGRRGRGGGGGGYYYYYYYYYYYY",
//            "QQQQQQYWWWWWOOOOVVOVOOOOOOOVVVVZZLLLLDDDDDDLJJJJJJJJJMMMMMMMMMMAAAAAAAAKKKKKRRRKKKKSZZWWWWWWWWOOOOOOOOOOOOOOOOOOOOORRRRRRRRGGGMMYYYYYYYYYYYY",
//            "QQQQQQYWWWWWWWWVVVVVVOOOOOVVAAVLLLLLLLLLDDLLLLJJJJJJJMMMMMMMMMMTTTTDAAAKKKKKRRRAAAEEEZWWWWWWWWOOOOOOOOOOOOOOOOOOORRRRRRRRRGGMGGMYMYYYYYYYYYY",
//            "QQQQQQYWWWWWWWWWAVVVVOOOOOVVVVVLLLLLLLLLLLLLLLJJJJJJJMJMMMMMMMTTTTTTTAAKKKKKRRRAAAEEWWWWWWLWLLOOOOOOOOOOOQQQOOOOOORRRRRRRRMMMMMMMMMYYYYYYYYY",
//            "QQQQQWWWWWWWWWWWAAAVVOOOOOOVMVRLLLLLLLLLLLLLLJJJJJJJJJJJMMMMMMTTTTTTTRRRRRKKRRRAEEEEEEEEEWLLLLLIOOOOOOOOOMQQOOOOOORRRRRRRMMMMMMMMMMMYYYYYYYH",
//            "QWQQWWWWWWWWWWWWWAAVVOOOOCVVVRRRLLLLLLLLLLLLLJJJJJJJJVVVMMMMMMTTTTTTTRRRRRKKRRRIEEEEEEEEELLLLLLIIIOOOOQQQQQQOOOORRRRRRRRRMMMMMMMMMNMYGGGGGGQ",
//            "WWWQWWWWWWWWWWWWWWWWDDDOOOOORRRLLLLLLLLLLLLLLLJJJJJJJVVVMMMMVVTTTTTTARRRRRKKRRRREEEEEEEEELLLLLLLQQQOOQQQQQQQOOORRRRRRRRRRMMMMMMMMMMMGGGGGGGQ",
//            "WWQQQWWWWWWWWWWWWWWWDDDOOORRRRRRRLRRLLLLLLLLLLJJJJJJVVVVVVVMVVVVTTHXXRRRRRRRRRRREEEEWEEEELLLLLIQQQQOQQQQQQQQQOOORRRRRRRRRMMMMMMMMMMMMGQQGQQQ",
//            "WQQWWWWWWWWWWWWWWWWDDDOOOOAAAAARRRRRLLLLLLLLLJJJJJJJVVVVVVVVVVVTTHHXXRRRRRRRRRRRIEEEEEEELLLLLQIQQQQQQQQQQQQQQOORRRRRRRRRRRMMMMMMMMMMMQQQGQQQ",
//            "WQWWWWWWWWWWWWWWAWWDDXOXSSSSAAAARRRRLLLLLLWLLLJJJJVVVSSSSVVVVVVHHHXEXRRRRRRRRRRRIEEEELELLLLLLQIQQQQQQQQQQQQQQQQJRRRRRRRRRRMMMMMMMMMMLLQQQQQQ",
//            "WWWWWWWWWWWXXWWWAAXXXXXXSSSAAAAARRRLLLLLLLLULJJJJJJVVSSBSVVVVVVVXXXXXRRRRRXIIRRRLEEEELELLLLLQQQQQQQQQQQQQQQQQQJJJRRRRRRRRRMMMMMMMMMMMMQQQQQQ",
//            "WWWWWWWWWWWXXXWWAXXXXXXXKSAAAAAARRRLXLLLLLLLLLLBJJSVVSSSSSVVVVVXXXXXXRRRRRXXIIILLLLLELLLLLLLQQQQQQQQQQQQQQQQQQJJRRRRRRRRRMMMMMMMMMMMMMQQQQQQ",
//            "WWWWWWWWWXXXXXXXXXXXXXXXAAAAAAAAAAASLLLLLLLLLLLLPPSSVSSSSSSSSVVXXXXXXRRRRRXXIIILLLLLLLLLLLLLLQQQQQQQQQQQQQQQQJJJJRRRRRRRRRMMMMMMMMMMMMMQQQQQ",
//            "WWWWWWWWWWXXXXXXXXXXXXSSAAAAAAAASASSLLSSSLLLLLLLLLSSTSSSSSQSQQVXXXXXXRRRRRXXXXLLLLLLLLLLLLLLLLLLQQQQQQQQQQQQJJJJJRRRRARRRAAAMMMMMMMMCCQQQQQQ",
//            "WWWWWWWWWWXXXXXXXXXXXSSSAAAAAAASSSSSSSSSLLLLLLLLSSSSSSSSSSQQQQXXXXXXXXXXXXXXXLLLLLLLLLLLLLLLLLLLLQQQQQQSQQQQQJJJJRRRAAARRAAAAMMMMMMCCCCCCQQQ",
//            "WWWWWWWWWWXXXXXXXXXXXSSSASSAAAASSSSSSSSSSLLSSSSLLSSSSSSSSSQQQQXXXXXXXXXXXXOOOLLLLLLLLLLLLLLLLLLLLQQQQQQSSSQQQJJJJRRRAAAARAAAMMMMMCCCCCCCCCCQ",
//            "WWWWWWWWWXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSQQQQXXXXXXXXXXXXOOOLLLLLLLLLLLLLLLLLLLQQQQQSSSSSQJJJJJJJRRAAAAAAAAMMMMMCCCCCCCCCCC",
//
//)